const $=(s,r=document)=>r.querySelector(s);const api=async(path,opt={})=>{const r=await fetch('/api'+path,{credentials:'include',...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({ok:false,error:'Invalid response'}));if(!r.ok||!d.ok)throw new Error(d.error||'Request failed');return d};const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function layout(){return `<div class="shell"><header class="topbar"><div class="brand">BlueWave Admin</div><button class="btn" id="out">Logout</button></header><div class="layout"><aside class="sidebar"><nav class="nav"><a href="#dash">📊 Dashboard</a><a href="#users">👥 Users</a><a href="#posts">📝 Posts</a></nav></aside><main><div id="adminContent"></div></main><aside class="rightbar"><div class="card section"><h3>Quick note</h3><p class="muted">Moderation changes are immediate.</p></div></aside></div></div>`}
async function login(){document.body.innerHTML=`<div class="auth-wrap"><div class="auth-card card"><div class="brand">BlueWave Admin</div><h1>Control panel</h1><div class="field"><label>Username</label><input id="u"></div><div class="field"><label>Password</label><input id="p" type="password"></div><button class="btn primary full" id="go">Sign in</button><div id="m"></div></div></div>`;$('#go').onclick=async()=>{try{await api('/admin/login',{method:'POST',body:JSON.stringify({username:$('#u').value,password:$('#p').value})});location.hash='#dash'}catch(e){$('#m').className='error';$('#m').textContent=e.message}}}
async function data(){return api('/admin/data')}
async function dash(){const d=await data();$('#adminContent').innerHTML=`<h1>Dashboard</h1><div class="admin-grid"><div class="card stat"><div class="muted">Users</div><b>${d.stats.users}</b></div><div class="card stat"><div class="muted">Posts</div><b>${d.stats.posts}</b></div><div class="card stat"><div class="muted">Live</div><b>${d.stats.online}</b></div><div class="card stat"><div class="muted">Server</div><b>OK</b></div></div>`}
async function users(){const d=await data();$('#adminContent').innerHTML=`<div class="card section"><h1>Users</h1><div style="overflow:auto"><table class="admin-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Created</th><th>Action</th></tr></thead><tbody>${d.users.map(u=>`<tr><td><b>${esc(u.name)}</b><br><span class="muted">@${esc(u.username)}</span></td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td>${new Date(u.createdAt).toLocaleDateString()}</td><td><button class="btn" data-role="${u.uid}" data-next="${u.role==='admin'?'user':'admin'}">${u.role==='admin'?'Make user':'Make admin'}</button></td></tr>`).join('')}</tbody></table></div></div>`;document.querySelectorAll('[data-role]').forEach(b=>b.onclick=async()=>{await api('/admin/users/'+b.dataset.role+'/role',{method:'POST',body:JSON.stringify({role:b.dataset.next})});users()})}
async function posts(){const d=await data();$('#adminContent').innerHTML=`<div class="card section"><h1>Posts</h1><div class="list">${d.posts.map(p=>`<div class="list-item"><div><b>${esc(p.text||'📷 Photo post')}</b><div class="muted">${new Date(p.createdAt).toLocaleString()} · ❤️ ${p.likeCount||0} · 💬 ${p.commentCount||0}</div></div><button class="btn danger" data-del="${p.id}">Delete</button></div>`).join('')||'<div class="muted">No posts.</div>'}</div></div>`;document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this post?')){await api('/admin/posts/'+b.dataset.del,{method:'DELETE'});posts()}})}
async function route(){if(!document.body.querySelector('.shell')){try{await api('/auth/me');}catch{};return login()}if(location.hash==='#users')return users();if(location.hash==='#posts')return posts();return dash()}
async function start(){try{await api('/admin/data');document.body.innerHTML=layout();$('#out').onclick=async()=>{await api('/admin/logout',{method:'POST'});location.reload()};route()}catch{login()}}window.addEventListener('hashchange',route);window.addEventListener('load',start);
