const $=(s,r=document)=>r.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const api=async(p,o={})=>{const r=await fetch('/api'+p,{credentials:'include',...o,headers:{'content-type':'application/json',...(o.headers||{})}});const d=await r.json().catch(()=>({ok:false,error:'Invalid response'}));if(!r.ok||!d.ok)throw new Error(d.error||'Request failed');return d};
function toast(x){const e=document.createElement('div');e.className='toast';e.textContent=x;$('#toastRoot').append(e);setTimeout(()=>e.remove(),2200)}
function login(){document.body.innerHTML=`<div class="auth-screen"><div class="auth-shell" style="max-width:560px"><div class="auth-brand-block"><div class="brand-mark">B</div><div><div class="brand-name">BlueWave Admin</div><div class="brand-tag">Control center</div></div></div><div class="auth-card" style="margin-top:45px"><h2 style="margin:0">Admin sign in</h2><p class="auth-sub">Use your Vercel admin credentials.</p><div class="field"><label>Username<input id="u" autocomplete="username"></label></div><div class="field"><label>Password<input id="p" type="password" autocomplete="current-password"></label></div><button class="primary-btn wide" id="go">Sign in</button><div id="m" class="form-msg"></div></div></div></div>`;$('#go').onclick=async()=>{try{await api('/admin/login',{method:'POST',body:JSON.stringify({username:$('#u').value,password:$('#p').value})});location.reload()}catch(e){$('#m').className='form-msg error';$('#m').textContent=e.message}}}
function layout(){document.body.innerHTML=`<div class="app-screen"><header class="topbar"><div class="brand"><span class="brand-mark small">B</span>BlueWave Admin</div><div></div><div class="top-actions"><button class="tiny-btn" id="out">Log out</button></div></header><div class="page-shell"><aside class="left-rail"><nav class="main-nav"><a href="#dash">📊 Dashboard</a><a href="#users">👥 Users</a><a href="#posts">📝 Posts</a></nav></aside><main class="main-column"><div id="adminView"></div></main><aside class="right-rail"><div class="card panel"><h3 style="margin:0 0 8px">Admin</h3><div class="muted">Changes are applied immediately.</div></div></aside></div></div><div id="toastRoot" class="toast-root"></div>`;$('#out').onclick=async()=>{await api('/admin/logout',{method:'POST'});location.reload()}}
async function data(){return api('/admin/data')}
async function dash(){const d=await data();$('#adminView').innerHTML=`<div class="view-header"><h1 class="view-title">Dashboard</h1></div><div class="admin-grid" style="display:grid;grid-template-columns:repeat(4,1fr);gap:14px"><div class="card stat"><div class="muted">Users</div><b>${d.stats.users}</b></div><div class="card stat"><div class="muted">Posts</div><b>${d.stats.posts}</b></div><div class="card stat"><div class="muted">Live</div><b>${d.stats.online}</b></div><div class="card stat"><div class="muted">Status</div><b>Online</b></div></div><div class="card section-card" style="margin-top:14px"><h3 style="margin-top:0">Quick view</h3><p class="muted">Manage accounts, moderate posts and track activity from the left menu.</p></div>`}
async function users(){const d=await data();$('#adminView').innerHTML=`<div class="view-header"><h1 class="view-title">Users</h1></div><div class="card section-card" style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:left;padding:10px">User</th><th style="text-align:left;padding:10px">Email</th><th style="text-align:left;padding:10px">Role</th><th style="text-align:left;padding:10px">Action</th></tr></thead><tbody>${d.users.map(u=>`<tr style="border-top:1px solid var(--line)"><td style="padding:10px"><div class="person"><img class="avatar sm" src="${esc(u.photoURL||'/avatar.svg')}"><div><b>${esc(u.name)}</b><div class="muted">@${esc(u.username)}</div></div></div></td><td style="padding:10px">${esc(u.email)}</td><td style="padding:10px">${esc(u.role)}</td><td style="padding:10px"><button class="tiny-btn" data-role="${esc(u.uid)}" data-next="${u.role==='admin'?'user':'admin'}">${u.role==='admin'?'Make user':'Make admin'}</button></td></tr>`).join('')}</tbody></table></div>`;$$('[data-role]').forEach(b=>b.onclick=async()=>{await api('/admin/users/'+b.dataset.role+'/role',{method:'POST',body:JSON.stringify({role:b.dataset.next})});toast('Role updated');users()})}
async function posts(){const d=await data();$('#adminView').innerHTML=`<div class="view-header"><h1 class="view-title">Posts</h1></div><div class="card section-card">${d.posts.map(p=>`<div class="search-user"><div><b>${esc(p.text||'📷 Photo post')}</b><div class="muted">${new Date(p.createdAt).toLocaleString()} · ❤️ ${p.likeCount||0} · 💬 ${p.commentCount||0}</div></div><button class="tiny-btn" data-del="${esc(p.id)}">Delete</button></div>`).join('')||'<div class="empty">No posts.</div>'}</div>`;$$('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this post?')){await api('/admin/posts/'+b.dataset.del,{method:'DELETE'});toast('Post deleted');posts()}})}
async function start(){try{await api('/admin/data');layout();route()}catch{login()}}
async function route(){if(location.hash==='#users')return users();if(location.hash==='#posts')return posts();return dash()}window.addEventListener('hashchange',route);window.addEventListener('load',start);
