const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const api=async(path,opt={})=>{const headers={...(opt.body instanceof FormData?{}:{'content-type':'application/json'}),...(opt.headers||{})};const r=await fetch('/api'+path,{credentials:'include',...opt,headers});const d=await r.json().catch(()=>({ok:false,error:'Invalid server response'}));if(!r.ok||!d.ok)throw new Error(d.error||'Request failed');return d};
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
let me=null, activeChat=null, chatTimer=null, searchTimer=null;
function toast(msg){const root=$('#toastRoot');const e=document.createElement('div');e.className='toast';e.textContent=msg;root.append(e);setTimeout(()=>e.remove(),2800)}
function avatar(url){return esc(url||'/avatar.svg')}
async function getMe(){const d=await api('/auth/me');me=d.user;return me}
function authTabs(){document.addEventListener('click',e=>{const b=e.target.closest('[data-auth]');if(!b)return;$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',b.dataset.auth!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.auth!=='register')})}
async function bindAuth(){
  $('#loginBtn').onclick=async()=>{const m=$('#loginMsg');m.className='form-msg';m.textContent='';try{await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value})});await bootApp()}catch(e){m.className='form-msg error';m.textContent=e.message}};
  $('#registerBtn').onclick=async()=>{const m=$('#registerMsg');m.className='form-msg';m.textContent='';try{await api('/auth/register',{method:'POST',body:JSON.stringify({email:$('#regEmail').value.trim(),username:$('#regUsername').value.trim(),name:$('#regName').value.trim(),password:$('#regPassword').value})});await bootApp()}catch(e){m.className='form-msg error';m.textContent=e.message}};
}
function shellReady(user){$('#authScreen').classList.add('hidden');$('#appScreen').classList.remove('hidden');$('#railName').textContent=user.name||'You';$('#railUsername').textContent='@'+(user.username||'user');$('#railAvatar,#meAvatar').forEach(x=>{x.src=user.photoURL||'/avatar.svg';x.onerror=()=>x.src='/avatar.svg'});}
function navActive(name){$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===name))}
function homeTemplate(){return `<div class="view-header"><h1 class="view-title">Home</h1><button class="tiny-btn" id="refreshFeed">Refresh</button></div><div class="card composer"><div class="composer-top"><img class="avatar" src="${avatar(me?.photoURL)}"><textarea id="postText" placeholder="What’s happening?"></textarea></div><div class="composer-bottom"><label class="photo-label">📷 Photo<input id="postFile" type="file" accept="image/*" hidden></label><button class="primary-btn" id="postBtn">Post</button></div><div id="composerNote" class="muted" style="margin-top:8px;font-size:12px"></div></div><div id="feed" class="card feed"></div>`}
function postCard(p){const a=p.author||{};return `<article class="post" data-post="${esc(p.id)}"><div class="post-head"><a href="#user/${encodeURIComponent(p.authorId)}"><img class="avatar" src="${avatar(a.photoURL)}" onerror="this.src='/avatar.svg'"></a><div class="user-meta"><b>${esc(a.name||'User')}</b><span>@${esc(a.username||'user')} · ${new Date(p.createdAt).toLocaleString()}</span></div></div>${p.text?`<div class="post-text">${esc(p.text)}</div>`:''}${p.imageURL?`<img class="post-image" src="${esc(p.imageURL)}" loading="lazy" alt="Post image">`:''}<div class="post-actions"><button data-act="like">❤️ ${p.likeCount||0}</button><button data-act="comment">💬 ${p.commentCount||0}</button><button data-act="bookmark">🔖</button><button data-act="share">↗ Share</button></div><div class="comments hidden"></div></article>`}
async function upload(file){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/upload',{method:'POST',credentials:'include',body:fd});const d=await r.json().catch(()=>({ok:false,error:'Invalid upload response'}));if(!r.ok||!d.ok)throw new Error(d.error||'Upload failed');return d.url}
async function renderFeed(mode=''){const box=$('#feed');if(!box)return;box.innerHTML='<div class="empty">Loading posts…</div>';try{const d=await api('/feed'+(mode?'?mode='+encodeURIComponent(mode):''));box.innerHTML=d.posts.length?d.posts.map(postCard).join(''):'<div class="empty"><h3>No posts yet</h3><div>Create the first post or follow someone.</div></div>'}catch(e){box.innerHTML=`<div class="empty error">${esc(e.message)}</div>`}}
async function home(){navActive('home');$('#view').innerHTML=homeTemplate();$('#postFile').onchange=()=>$('#composerNote').textContent=$('#postFile').files[0]?.name||'';const submit=async()=>{try{let imageURL='';const f=$('#postFile').files[0];if(f){$('#postBtn').disabled=true;imageURL=await upload(f)}const text=$('#postText').value.trim();if(!text&&!imageURL)throw new Error('Write something or add a photo.');await api('/posts',{method:'POST',body:JSON.stringify({text,imageURL})});$('#postText').value='';$('#postFile').value='';$('#composerNote').textContent='';toast('Posted');await renderFeed()}catch(e){toast(e.message)}finally{$('#postBtn').disabled=false}};$('#postBtn').onclick=submit;$('#refreshFeed').onclick=()=>renderFeed();await renderFeed()}
async function explore(){navActive('explore');$('#view').innerHTML=`<div class="view-header"><h1 class="view-title">Explore</h1></div><div class="card search-card"><div class="field"><label>Find people</label><input id="exploreSearch" placeholder="Search username"></div><div id="exploreResults"></div></div><div class="card feed" id="feed"></div>`;$('#exploreSearch').oninput=e=>searchUsers(e.target.value,'#exploreResults');await renderFeed('explore')}
async function searchUsers(q,target){const box=$(target);if(!q.trim()){box.innerHTML='';return}clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{try{const d=await api('/users/search?q='+encodeURIComponent(q.trim()));box.innerHTML=d.users.map(u=>`<div class="search-user"><div class="person"><img class="avatar sm" src="${avatar(u.photoURL)}"><div><b>${esc(u.name)}</b><div class="muted">@${esc(u.username)}</div></div></div><a class="tiny-btn" href="#user/${encodeURIComponent(u.uid)}">View</a></div>`).join('')||'<div class="muted" style="padding:12px 0">No people found.</div>'}catch(e){box.innerHTML=`<div class="error">${esc(e.message)}</div>`}},250)}
async function notifications(){navActive('notifications');try{const d=await api('/notifications');$('#view').innerHTML=`<div class="view-header"><h1 class="view-title">Notifications</h1></div><div class="card section-card">${d.notifications.map(n=>`<div class="search-user"><div>${n.type==='follow'?'👤 Someone followed you':n.type==='like'?'❤️ Someone liked your post':'🔔 New activity'}</div><span class="muted">${new Date(n.createdAt).toLocaleString()}</span></div>`).join('')||'<div class="empty">No notifications yet.</div>'}</div>`}catch(e){$('#view').innerHTML=`<div class="card section-card error">${esc(e.message)}</div>`}}
async function profile(id){navActive('profile');const uid=id||me.uid;try{const d=await api('/users/'+encodeURIComponent(uid));const u=d.user;const self=uid===me.uid;$('#view').innerHTML=`<div class="card"><div class="profile-cover" style="background-image:url('${esc(u.coverURL||'')}')"></div><div class="profile-overlap"><div class="profile-head-row"><div class="profile-info"><img class="avatar lg" src="${avatar(u.photoURL)}" onerror="this.src='/avatar.svg'"><h2>${esc(u.name)}</h2><div class="muted">@${esc(u.username)}</div><p>${esc(u.bio||'')}</p><div class="muted">${u.followersCount||0} followers · ${u.followingCount||0} following</div></div>${self?'<a class="tiny-btn primary" href="#settings">Edit profile</a>':`<button class="tiny-btn ${d.following?'':'primary'}" id="followProfile">${d.following?'Following':'Follow'}</button>`}</div><div class="profile-tabs"><a href="#followers/${encodeURIComponent(uid)}">Followers</a><a href="#following/${encodeURIComponent(uid)}">Following</a><a href="#chats/${encodeURIComponent(uid)}">Message</a></div></div></div><div class="card feed" id="feed"></div>`;if(!self){$('#followProfile').onclick=async()=>{const r=await api('/users/'+uid+'/follow',{method:'POST'});toast(r.following?'Following':'Unfollowed');profile(uid)}}await renderFeed('explore')}catch(e){$('#view').innerHTML=`<div class="card section-card error">${esc(e.message)}</div>`}}
async function peopleList(uid,type){const d=await api('/users/'+uid+'/'+type);$('#view').innerHTML=`<div class="view-header"><h1 class="view-title">${type==='followers'?'Followers':'Following'}</h1></div><div class="card section-card">${d.users.map(u=>`<div class="search-user"><div class="person"><img class="avatar sm" src="${avatar(u.photoURL)}"><div><b>${esc(u.name)}</b><div class="muted">@${esc(u.username)}</div></div></div><a class="tiny-btn" href="#user/${encodeURIComponent(u.uid)}">View</a></div>`).join('')||'<div class="empty">No users here yet.</div>'}</div>`}
async function settings(){navActive('settings');const u=await getMe();$('#view').innerHTML=`<div class="view-header"><h1 class="view-title">Edit profile</h1></div><div class="card section-card"><div class="settings-grid"><div class="field"><label>Name<input id="pname" value="${esc(u.name)}"></label></div><div class="field"><label>Username<input value="@${esc(u.username)}" disabled></label></div></div><div class="field"><label>Bio<textarea id="pbio" rows="5">${esc(u.bio||'')}</textarea></label></div><div class="settings-grid"><div class="field"><label>Profile photo<input id="pfile" type="file" accept="image/*"></label></div><div class="field"><label>Cover photo<input id="cfile" type="file" accept="image/*"></label></div></div><button class="primary-btn" id="saveProfile">Save changes</button><div id="settingsMsg" style="margin-top:12px"></div></div>`;$('#saveProfile').onclick=async()=>{try{let photoURL=u.photoURL,coverURL=u.coverURL;if($('#pfile').files[0])photoURL=await upload($('#pfile').files[0]);if($('#cfile').files[0])coverURL=await upload($('#cfile').files[0]);await api('/profile',{method:'PUT',body:JSON.stringify({name:$('#pname').value.trim(),bio:$('#pbio').value,photoURL,coverURL})});me=await getMe();shellReady(me);toast('Profile updated');profile(me.uid)}catch(e){$('#settingsMsg').className='error';$('#settingsMsg').textContent=e.message}}}
async function openChat(otherId){const d=await api('/chats/open',{method:'POST',body:JSON.stringify({userId:otherId})});return d.chatId}
function chatHTML(){return `<div class="view-header"><h1 class="view-title">Messages</h1></div><div class="chat-grid"><div class="card chat-list" id="chatList"></div><div class="card chat-main"><div class="chat-header" id="chatHeader"><img class="avatar sm" src="/avatar.svg"><div><b>Select a conversation</b><div class="muted">Choose someone to start chatting</div></div></div><div id="messages" class="messages"><div class="empty">No conversation selected.</div></div><div class="chat-compose"><input id="chatInput" placeholder="Write a message…"><button class="primary-btn" id="sendMsg">Send</button></div></div></div>`}
async function chats(targetUser){navActive('chats');$('#view').innerHTML=chatHTML();try{const d=await api('/chats');const list=$('#chatList');list.innerHTML=d.chats.map(c=>`<div class="chat-item" data-chat-id="${esc(c.id)}" data-user-id="${esc(c.other?.uid||'')}"><div class="person"><img class="avatar sm" src="${avatar(c.other?.photoURL)}"><div><b>${esc(c.other?.name||'Chat')}</b><div class="muted">${esc(c.lastMessage||'No messages yet')}</div></div></div></div>`).join('')||'<div class="empty">No chats yet.</div>';$$('.chat-item').forEach(x=>x.onclick=()=>selectChat(x.dataset.chatId,x.dataset.userId,x));if(targetUser){const id=await openChat(targetUser);const node=$$('[data-user-id]').find(x=>x.dataset.userId===targetUser);await selectChat(id,targetUser,node)} }catch(e){$('#chatList').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function selectChat(chatId,userId,node){activeChat={chatId,userId};$$('.chat-item').forEach(x=>x.classList.toggle('active',x===node));const u=await api('/users/'+encodeURIComponent(userId));$('#chatHeader').innerHTML=`<img class="avatar sm" src="${avatar(u.user.photoURL)}"><div><b>${esc(u.user.name)}</b><div class="muted">@${esc(u.user.username)}</div></div>`;await loadMessages();clearInterval(chatTimer);chatTimer=setInterval(loadMessages,3000)}
async function loadMessages(){if(!activeChat)return;try{const d=await api('/chats/'+encodeURIComponent(activeChat.chatId)+'/messages');const box=$('#messages');box.innerHTML=d.messages.map(m=>`<div class="bubble ${m.senderId===me.uid?'mine':'theirs'}">${m.imageURL?`<img src="${esc(m.imageURL)}" alt="">`:''}${m.text?`<div>${esc(m.text)}</div>`:''}<div style="font-size:10px;opacity:.65;margin-top:5px">${new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div></div>`).join('')||'<div class="empty">Say hello 👋</div>';box.scrollTop=box.scrollHeight}catch(e){toast(e.message)}}
async function sendMessage(){if(!activeChat)return toast('Open a conversation first');const text=$('#chatInput').value.trim();if(!text)return;try{await api('/chats/'+encodeURIComponent(activeChat.chatId)+'/messages',{method:'POST',body:JSON.stringify({text})});$('#chatInput').value='';await loadMessages()}catch(e){toast(e.message)}}
async function chatsBind(){const b=$('#sendMsg');if(b)b.onclick=sendMessage;const i=$('#chatInput');if(i)i.onkeydown=e=>{if(e.key==='Enter')sendMessage()}}
async function loadSide(){try{const d=await api('/users/suggestions');$('#suggestions').innerHTML=d.users.map(u=>`<div class="follow-row"><div class="person"><img class="avatar sm" src="${avatar(u.photoURL)}"><div class="truncate"><b>${esc(u.name)}</b><div class="muted">@${esc(u.username)}</div></div></div><button class="tiny-btn primary" data-follow="${esc(u.uid)}">Follow</button></div>`).join('')||'<div class="muted">No suggestions yet.</div>'}catch(e){$('#suggestions').innerHTML='<div class="muted">No suggestions available.</div>'}try{const t=await api('/trending');$('#trending').innerHTML=t.hashtags.map(x=>`<div class="trend-row"><span>${esc(x.tag)}</span><b>${x.count}</b></div>`).join('')||'<div class="muted">No trends yet.</div>'}catch{}}
async function doSearchTop(q){if(!q.trim()){$('#searchDrop').classList.add('hidden');return}try{const d=await api('/users/search?q='+encodeURIComponent(q.trim()));$('#searchDrop').innerHTML=d.users.map(u=>`<a class="drop-item" href="#user/${encodeURIComponent(u.uid)}"><img class="avatar sm" src="${avatar(u.photoURL)}"><div><b>${esc(u.name)}</b><div class="muted">@${esc(u.username)}</div></div></a>`).join('')||'<div class="muted" style="padding:12px">No results</div>';$('#searchDrop').classList.remove('hidden')}catch{}}
function bindGlobal(){
  document.addEventListener('click',async e=>{
    const f=e.target.closest('[data-follow]');
    if(f){
      try{
        const r=await api('/users/'+f.dataset.follow+'/follow',{method:'POST'});
        f.textContent=r.following?'Following':'Follow';
        f.classList.toggle('primary',r.following===false);
        toast(r.following?'Following':'Unfollowed');
      }catch(x){toast(x.message)}
      return;
    }
    const b=e.target.closest('[data-act]');
    if(!b)return;
    const p=e.target.closest('[data-post]'); if(!p)return;
    const id=p.dataset.post;
    try{
      if(b.dataset.act==='like'){
        const n=Number((b.textContent.match(/\d+/)||['0'])[0]);
        const r=await api('/posts/'+id+'/like',{method:'POST'});
        b.textContent=(r.liked?'❤️':'♡')+' '+Math.max(0,n+(r.liked?1:-1));
      }else if(b.dataset.act==='bookmark'){
        const r=await api('/posts/'+id+'/bookmark',{method:'POST'});
        toast(r.bookmarked?'Saved':'Removed from bookmarks');
      }else if(b.dataset.act==='share'){
        await api('/posts/'+id+'/share',{method:'POST'});
        const url=location.origin+location.pathname+'#post/'+id;
        try{if(navigator.clipboard)await navigator.clipboard.writeText(url)}catch{}
        toast('Post link copied');
      }else if(b.dataset.act==='comment'){
        const box=$('.comments',p); if(!box)return;
        box.classList.toggle('hidden');
        if(box.dataset.loaded) return;
        const d=await api('/posts/'+id+'/comments');
        box.innerHTML=`<div class="comment-box"><input class="comment-input" placeholder="Write a reply…"><button class="tiny-btn primary comment-send">Reply</button></div>`+d.comments.map(c=>`<div class="comment-item"><b>${esc(c.userName||'User')}</b><div>${esc(c.text)}</div></div>`).join('');
        const input=$('.comment-input',box),btn=$('.comment-send',box);
        btn.onclick=async()=>{
          const text=input.value.trim(); if(!text)return;
          try{await api('/posts/'+id+'/comments',{method:'POST',body:JSON.stringify({text})});input.value='';box.dataset.loaded='';box.classList.add('hidden');await renderFeed()}catch(x){toast(x.message)}
        };
        input.onkeydown=x=>{if(x.key==='Enter')btn.click()};
        box.dataset.loaded='1';
      }
    }catch(x){toast(x.message)}
  });
  const gs=$('#globalSearch');
  if(gs){
    gs.oninput=e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>doSearchTop(e.target.value),250)};
    gs.onfocus=e=>doSearchTop(e.target.value);
    document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('#searchDrop')?.classList.add('hidden')});
  }
  $('#logoutBtn').onclick=async()=>{try{await api('/auth/logout',{method:'POST'})}finally{location.reload()}};
  $('#meAvatarBtn').onclick=()=>location.hash='#profile';
  $('#notifTop').onclick=()=>location.hash='#notifications';
  $('#railPost').onclick=()=>{location.hash='#home';setTimeout(()=>$('#postText')?.focus(),80)};
}
async function router(){const h=location.hash||'#home';if(!me)return;try{if(h==='#home')return home();if(h==='#explore')return explore();if(h==='#notifications')return notifications();if(h==='#chats'){await chats();return chatsBind()}if(h.startsWith('#chats/')){await chats(h.split('/')[1]);return chatsBind()}if(h==='#profile')return profile(me.uid);if(h.startsWith('#user/'))return profile(decodeURIComponent(h.slice(6)));if(h.startsWith('#followers/'))return peopleList(decodeURIComponent(h.slice(11)),'followers');if(h.startsWith('#following/'))return peopleList(decodeURIComponent(h.slice(11)),'following');if(h==='#settings')return settings();return home()}catch(e){$('#view').innerHTML=`<div class="card section-card error">${esc(e.message)}</div>`}}
async function bootApp(){try{me=await getMe();if(!me){$('#authScreen').classList.remove('hidden');$('#appScreen').classList.add('hidden');return}shellReady(me);bindGlobal();await loadSide();await router();setInterval(async()=>{try{const d=await api('/auth/me');if(d.user){me=d.user;shellReady(me)}}catch{}},60000)}catch(e){$('#authScreen').classList.remove('hidden');toast(e.message)}}
window.addEventListener('hashchange',router);window.addEventListener('load',async()=>{authTabs();await bindAuth();await bootApp()});
