(() => {
  'use strict';
  const $ = (s, r = document) => r.querySelector(s);
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const app = $('#app');
  let ME = null;
  const STATE = { page: 'home', profile: '', chat: '', searchTimer: null, chatTimer: null };

  function hideBoot() { const f = $('#bootFallback'); if (f) f.remove(); }
  function toast(message, kind = 'info') { const n = document.createElement('div'); n.className = `toast ${kind}`; n.textContent = message; document.body.appendChild(n); setTimeout(() => n.remove(), 2800); }
  async function api(url, opts = {}) {
    const headers = { ...(opts.headers || {}) };
    if (opts.body && !(opts.body instanceof FormData)) headers['Content-Type'] = 'application/json';
    const res = await fetch(url, { credentials: 'same-origin', ...opts, headers });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) throw new Error(data.error || `Request failed (${res.status})`);
    return data;
  }
  function avatar(user, size = '') {
    const letter = esc((user?.displayName || user?.username || '?').slice(0,1).toUpperCase());
    return `<div class="avatar ${size}">${user?.avatarUrl ? `<img src="${esc(user.avatarUrl)}" alt="">` : letter}</div>`;
  }
  function relativeTime(v) {
    if (!v) return 'now';
    const sec = v.seconds ?? v._seconds ?? Math.floor(new Date(v).getTime() / 1000);
    const d = Math.max(0, Math.floor(Date.now() / 1000) - sec);
    if (d < 60) return `${Math.max(1,d)}s`;
    if (d < 3600) return `${Math.floor(d/60)}m`;
    if (d < 86400) return `${Math.floor(d/3600)}h`;
    if (d < 604800) return `${Math.floor(d/86400)}d`;
    return new Date(sec * 1000).toLocaleDateString();
  }
  function openModal(html, cls='') {
    const root = document.createElement('div'); root.className = `modal-layer ${cls}`; root.innerHTML = `<div class="modal-card">${html}</div>`;
    root.addEventListener('click', e => { if (e.target === root) root.remove(); }); document.body.appendChild(root); return root;
  }
  function loading(text='Loading…') { return `<div class="card loading-card"><span class="spinner"></span>${esc(text)}</div>`; }
  function empty(title, sub='') { return `<div class="card empty-state"><div class="empty-icon">⌁</div><h3>${esc(title)}</h3>${sub?`<p>${esc(sub)}</p>`:''}</div>`; }

  async function init() {
    try { const d = await api('/api/auth/me'); ME = d.user || null; hideBoot(); ME ? renderShell() : renderAuth(); } catch { hideBoot(); renderAuth(); }
  }

  function renderAuth() {
    document.body.className = 'auth-body';
    app.innerHTML = `<main class="auth-screen">
      <section class="auth-showcase">
        <div class="brand-lockup"><span class="logo-dot">B</span><div><strong>BlueWave</strong><small>Social, simply.</small></div></div>
        <div class="showcase-copy"><span class="eyebrow">A place to post, connect & chat</span><h1>Share your world.<br><span>Find your people.</span></h1><p>A clean social space for thoughts, photos, conversations and the people you care about.</p><div class="showcase-pills"><span>✦ Posts</span><span>◎ Profiles</span><span>◌ Private chat</span></div></div>
      </section>
      <section class="auth-panel">
        <div class="auth-card">
          <div class="auth-heading"><span class="auth-kicker">Welcome</span><h2 id="authTitle">Log in to BlueWave</h2><p id="authSub">Your timeline is waiting.</p></div>
          <form id="authForm" class="form-stack">
            <label>Username<input id="username" required minlength="3" maxlength="24" autocomplete="username" placeholder="e.g. mintu"></label>
            <label id="displayWrap" class="hidden">Display name<input id="displayName" maxlength="60" autocomplete="name" placeholder="Your name"></label>
            <label>Password<input id="password" type="password" required minlength="6" autocomplete="current-password" placeholder="••••••••"></label>
            <button class="primary full" id="authBtn">Log in</button>
          </form>
          <div class="auth-switch"><span id="switchText">New to BlueWave?</span> <button id="switchBtn" class="text-btn">Create account</button></div>
          <div class="auth-note">By continuing, you agree to use BlueWave responsibly.</div>
        </div>
      </section>
    </main>`;
    let login = true;
    $('#switchBtn').onclick = () => { login=!login; $('#authTitle').textContent=login?'Log in to BlueWave':'Create your BlueWave account'; $('#authSub').textContent=login?'Your timeline is waiting.':'Pick a username and join the wave.'; $('#displayWrap').classList.toggle('hidden', login); $('#authBtn').textContent=login?'Log in':'Create account'; $('#switchText').textContent=login?'New to BlueWave?':'Already have an account?'; $('#switchBtn').textContent=login?'Create account':'Log in'; $('#password').autocomplete=login?'current-password':'new-password'; };
    $('#authForm').onsubmit = async (e) => { e.preventDefault(); const btn=$('#authBtn'); btn.disabled=true; try { const body={username:$('#username').value,password:$('#password').value,displayName:$('#displayName').value}; const d=await api(login?'/api/auth/login':'/api/auth/register',{method:'POST',body:JSON.stringify(body)}); ME=d.user; renderShell(); await loadPage('home'); } catch(err){ toast(err.message,'error'); } finally { btn.disabled=false; } };
  }

  function renderShell() {
    document.body.className = '';
    app.innerHTML = `<div class="site-shell">
      <header class="topbar"><div class="topbar-inner"><button class="mobile-menu icon-button" id="mobileMenu">☰</button><a class="brand" href="#home"><span class="logo-dot">B</span><span>BlueWave</span></a><div class="global-search"><span>⌕</span><input id="globalSearch" placeholder="Search people or @username"><div id="searchResults" class="search-dropdown hidden"></div></div><div class="top-actions"><button class="icon-button" id="notifBtn" title="Notifications">♢<span id="notifBadge" class="badge-dot hidden"></span></button><button class="icon-button desktop-only" id="topMessages" title="Messages">✉</button><button class="user-chip" id="topProfile">${avatar(ME,'xs')}<span>@${esc(ME.username)}</span></button></div></div></header>
      <div class="app-grid"><aside class="sidebar left-sidebar" id="leftSidebar"><nav class="side-nav"><button data-nav="home">⌂ <span>Home</span></button><button data-nav="explore">⌕ <span>Explore</span></button><button data-nav="notifications">♢ <span>Notifications</span><b id="navNotifBadge" class="nav-badge hidden">0</b></button><button data-nav="messages">✉ <span>Messages</span></button><button data-nav="bookmarks">🔖 <span>Bookmarks</span></button><button data-nav="profile">◎ <span>Profile</span></button></nav><button class="primary full side-post" id="sidePost">＋ Create post</button><div class="sidebar-bottom"><button class="ghost full" id="logoutBtn">↪ Log out</button></div></aside><main id="main" class="main-column"></main><aside class="sidebar right-sidebar"><section class="rail-card"><div class="rail-head"><strong>Who to follow</strong></div><div id="suggestions">${loading('Loading…')}</div></section><section class="rail-card"><div class="rail-head"><strong>Trending</strong><span class="muted">Today</span></div><div id="trends">${loading('Loading…')}</div></section><section class="rail-footer"><span>BlueWave</span><span>·</span><span>Built for people</span></section></aside></div>
      <nav class="bottom-nav"><button data-nav="home">⌂<small>Home</small></button><button data-nav="explore">⌕<small>Explore</small></button><button data-nav="create">＋<small>Create</small></button><button data-nav="messages">✉<small>Chat</small></button><button data-nav="profile">◎<small>Profile</small></button></nav>
      <div id="globalModal"></div>
    </div>`;
    document.querySelectorAll('[data-nav]').forEach(b => b.addEventListener('click', () => loadPage(b.dataset.nav)));
    $('#sidePost').onclick=()=>loadPage('create'); $('#topMessages').onclick=()=>loadPage('messages'); $('#notifBtn').onclick=()=>loadPage('notifications'); $('#topProfile').onclick=()=>loadPage('profile'); $('#logoutBtn').onclick=logout;
    $('#globalSearch').addEventListener('input', ()=>{ clearTimeout(STATE.searchTimer); STATE.searchTimer=setTimeout(runSearch,230); });
    document.addEventListener('click', e=>{ if(!e.target.closest('.global-search')) $('#searchResults')?.classList.add('hidden'); });
    $('#mobileMenu').onclick=()=>$('#leftSidebar').classList.toggle('open');
    loadSuggestions(); loadTrends(); checkNotifications(); loadPage('home');
  }
  function setActive(page){ document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active', b.dataset.nav===page)); }
  async function loadPage(page, arg='') {
    STATE.page=page; if(page==='profile')STATE.profile=arg||ME.username; if(page==='messages')STATE.chat=arg||''; setActive(page); $('#leftSidebar')?.classList.remove('open');
    try {
      if(page==='home') return loadHome();
      if(page==='explore') return loadExplore();
      if(page==='create') return renderCreate();
      if(page==='profile') return loadProfile(STATE.profile);
      if(page==='messages') return loadMessages(STATE.chat);
      if(page==='notifications') return loadNotifications();
      if(page==='bookmarks') return loadBookmarks();
    } catch(e){ $('#main').innerHTML=empty('Something went wrong',e.message); }
  }

  function composer() { return `<section class="composer card"><div class="composer-row">${avatar(ME,'sm')}<textarea id="composerText" maxlength="1000" placeholder="What's on your mind, ${esc(ME.displayName||ME.username)}?"></textarea></div><div id="composerPreview"></div><div class="composer-foot"><label class="attach"><span>▧</span> Photo<input type="file" id="composeFile" accept="image/*"></label><button class="primary" id="postBtn">Post</button></div></section>`; }
  async function loadHome(){ const main=$('#main'); main.innerHTML=`${composer()}<div class="section-head"><div><span class="eyebrow">Your timeline</span><h2>Home</h2></div><button class="icon-button" id="refreshFeed">↻</button></div><div id="feed">${loading('Loading your feed…')}</div>`; bindComposer(); $('#refreshFeed').onclick=loadHome; try{const d=await api('/api/feed'); renderPosts(d.posts||[],'feed');}catch(e){$('#feed').innerHTML=empty('Your feed is empty',e.message);} }
  function renderCreate(){ const main=$('#main'); main.innerHTML=`<div class="page-head"><div><span class="eyebrow">Create</span><h1>Share something</h1><p>Post a thought or a photo for your people.</p></div></div>${composer()}<div class="hint-card">Tip: hashtags like <b>#bluewave</b> appear in Explore trends.</div>`; bindComposer(); }
  function bindComposer(){ const file=$('#composeFile'); if(file)file.onchange=()=>previewFile(file,$('#composerPreview')); $('#postBtn')?.addEventListener('click',()=>submitPost($('#composerText').value,file?.files?.[0]||null)); }
  function previewFile(input,target){ const f=input.files?.[0]; if(!f){target.innerHTML='';return} if(f.size>7*1024*1024){toast('Choose an image under 7 MB.','error');input.value='';return} const r=new FileReader();r.onload=()=>target.innerHTML=`<div class="preview-wrap"><img src="${r.result}" alt="Preview"><button class="preview-remove" type="button">×</button></div>`;r.readAsDataURL(f); target.onclick=e=>{if(e.target.classList.contains('preview-remove')){input.value='';target.innerHTML='';}}; }
  async function submitPost(text,file){ const btn=$('#postBtn');if(!text.trim()&&!file)return toast('Write something or add a photo.','error');btn.disabled=true;try{let imageUrl='';if(file)imageUrl=(await uploadFile(file)).url;await api('/api/posts',{method:'POST',body:JSON.stringify({text:text.trim(),imageUrl})});toast('Posted ✨','success');await loadHome();}catch(e){toast(e.message,'error');}finally{btn.disabled=false;} }
  async function uploadFile(file){const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});return api('/api/media/upload',{method:'POST',body:JSON.stringify({data})});}

  function postHTML(p){ const canDelete=p.author?.id===ME.id; return `<article class="post card"><div class="post-head"> <button class="avatar-button" data-profile="${esc(p.author?.username||'')}">${avatar(p.author,'md')}</button><div class="post-meta"><button class="name-link" data-profile="${esc(p.author?.username||'')}">${esc(p.author?.displayName||'User')}</button><div class="post-sub">@${esc(p.author?.username||'')} <span>·</span> ${relativeTime(p.createdAt)}</div></div>${canDelete?`<button class="icon-button danger-icon" data-delete="${esc(p.id)}">⌫</button>`:'<button class="icon-button muted-icon">•••</button>'}</div>${p.text?`<div class="post-text">${esc(p.text).replace(/(#[a-z0-9_]+)/gi,'<span class="hashtag">$1</span>')}</div>`:''}${p.imageUrl?`<img class="post-image" loading="lazy" src="${esc(p.imageUrl)}" alt="Post image">`:''}<div class="post-actions"><button data-like="${esc(p.id)}" class="${p.liked?'liked':''}"><span>${p.liked?'♥':'♡'}</span>${Number(p.likesCount||0)}</button><button data-comments="${esc(p.id)}"><span>💬</span>${Number(p.commentsCount||0)}</button><button data-bookmark="${esc(p.id)}" class="${p.bookmarked?'active':''}"><span>🔖</span>${p.bookmarked?'Saved':'Save'}</button><button data-share="${esc(p.id)}"><span>↗</span>Share</button></div></article>`; }
  function wirePosts(container){ container.querySelectorAll('[data-like]').forEach(b=>b.onclick=async()=>{try{const d=await api(`/api/posts/${b.dataset.like}/like`,{method:'POST'});b.classList.toggle('liked',d.liked);b.innerHTML=`<span>${d.liked?'♥':'♡'}</span>${d.likesCount||0}`;}catch(e){toast(e.message,'error')}}); container.querySelectorAll('[data-bookmark]').forEach(b=>b.onclick=async()=>{try{const d=await api(`/api/posts/${b.dataset.bookmark}/bookmark`,{method:'POST'});b.classList.toggle('active',d.bookmarked);b.innerHTML=`<span>🔖</span>${d.bookmarked?'Saved':'Save'}`}catch(e){toast(e.message,'error')}}); container.querySelectorAll('[data-comments]').forEach(b=>b.onclick=()=>comments(b.dataset.comments)); container.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(`${location.origin}/?post=${encodeURIComponent(b.dataset.share)}`);toast('Post link copied','success')}); container.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>loadPage('profile',b.dataset.profile)); container.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this post?'))return;try{await api(`/api/posts/${b.dataset.delete}`,{method:'DELETE'});toast('Post deleted','success');await loadPage(STATE.page)}catch(e){toast(e.message,'error')}}); }
  function renderPosts(posts,target){ const el=$('#'+target); if(!posts.length){el.innerHTML=empty('Nothing here yet','Follow people or create your first post.');return} el.innerHTML=posts.map(postHTML).join(''); wirePosts(el); }
  async function comments(id){ const modal=openModal(`<div class="modal-title"><div><span class="eyebrow">Post</span><h3>Comments</h3></div><button class="icon-button close-modal">×</button></div><div id="commentList" class="comment-list">${loading()}</div><form id="commentForm" class="comment-form"><input id="commentInput" maxlength="500" placeholder="Write a reply…"><button class="primary">Reply</button></form>`,'comment-modal'); modal.querySelector('.close-modal').onclick=()=>modal.remove(); try{const d=await api(`/api/posts/${id}/comments`); const list=modal.querySelector('#commentList'); list.innerHTML=d.comments.length?d.comments.map(c=>`<div class="comment-item">${avatar(c.author,'sm')}<div><b>${esc(c.author?.displayName||'User')}</b><small>@${esc(c.author?.username||'')} · ${relativeTime(c.createdAt)}</small><p>${esc(c.text)}</p></div></div>`).join(''):empty('No comments','Be the first to reply.'); modal.querySelector('#commentForm').onsubmit=async e=>{e.preventDefault();const input=modal.querySelector('#commentInput');if(!input.value.trim())return;try{await api(`/api/posts/${id}/comments`,{method:'POST',body:JSON.stringify({text:input.value})});input.value='';const d2=await api(`/api/posts/${id}/comments`);modal.querySelector('#commentList').innerHTML=d2.comments.map(c=>`<div class="comment-item">${avatar(c.author,'sm')}<div><b>${esc(c.author?.displayName||'User')}</b><small>@${esc(c.author?.username||'')}</small><p>${esc(c.text)}</p></div></div>`).join('');}catch(e){toast(e.message,'error')}};}catch(e){modal.querySelector('#commentList').innerHTML=empty('Could not load comments',e.message)} }

  async function loadExplore(){const main=$('#main');main.innerHTML=`<div class="page-head"><div><span class="eyebrow">Discover</span><h1>Explore</h1><p>See what people across BlueWave are talking about.</p></div></div><div class="explore-tabs"><button class="tab active">For you</button><button class="tab" id="trendingTab">Trending</button></div><div id="feed">${loading('Loading explore…')}</div>`; try{const d=await api('/api/explore');renderPosts(d.posts||[],'feed');}catch(e){$('#feed').innerHTML=empty('Explore is unavailable',e.message)} }

  async function loadProfile(username){ const main=$('#main'); main.innerHTML=loading('Loading profile…'); try{const [u,p]=await Promise.all([api(`/api/users/${encodeURIComponent(username)}`),api(`/api/users/${encodeURIComponent(username)}/posts`)]); const user=u.user; main.innerHTML=`<section class="profile-card card"><div class="cover"></div><div class="profile-body"><div class="profile-top"><div class="profile-avatar">${avatar(user,'xl')}</div>${user.id===ME.id?`<button class="secondary" id="editProfile">Edit profile</button>`:`<button class="primary" id="followBtn">${u.following?'Following':'Follow'}</button>`}</div><div class="profile-copy"><h1>${esc(user.displayName)} ${user.verified?'<span class="verified">✓</span>':''}</h1><div class="handle">@${esc(user.username)}</div><p>${esc(user.bio||'No bio yet.')}</p></div><div class="profile-stats"><button id="followersBtn"><b>${Number(user.followersCount||0)}</b><span>Followers</span></button><button id="followingBtn"><b>${Number(user.followingCount||0)}</b><span>Following</span></button><div><b>${p.posts?.length||0}</b><span>Posts</span></div></div></div></section><div class="section-head"><div><span class="eyebrow">Posts</span><h2>@${esc(user.username)}</h2></div></div><div id="profileFeed"></div>`; renderPosts(p.posts||[],'profileFeed'); if(user.id===ME.id)$('#editProfile').onclick=()=>editProfile(user); else $('#followBtn').onclick=async()=>{try{const d=await api(`/api/users/${encodeURIComponent(user.username)}/follow`,{method:'POST'});$('#followBtn').textContent=d.following?'Following':'Follow';await loadProfile(user.username);}catch(e){toast(e.message,'error')}}; $('#followersBtn').onclick=()=>peopleModal(user.username,'followers'); $('#followingBtn').onclick=()=>peopleModal(user.username,'following'); }catch(e){main.innerHTML=empty('Profile not found',e.message)} }
  async function editProfile(user){ const modal=openModal(`<div class="modal-title"><div><span class="eyebrow">Profile</span><h3>Edit profile</h3></div><button class="icon-button close">×</button></div><form id="profileForm" class="form-stack"><label>Display name<input id="pName" maxlength="60" value="${esc(user.displayName)}"></label><label>Bio<textarea id="pBio" maxlength="280" rows="4">${esc(user.bio||'')}</textarea></label><label>Avatar image<input id="pAvatarFile" type="file" accept="image/*"></label><label>Cover image<input id="pCoverFile" type="file" accept="image/*"></label><label>Avatar URL <span style="font-weight:500;color:#8b98ac">(optional)</span><input id="pAvatar" value="${esc(user.avatarUrl||'')}" placeholder="ImgBB image URL"></label><label>Cover URL <span style="font-weight:500;color:#8b98ac">(optional)</span><input id="pCover" value="${esc(user.coverUrl||'')}" placeholder="ImgBB image URL"></label><button class="primary full">Save changes</button></form>`);modal.querySelector('.close').onclick=()=>modal.remove();modal.querySelector('#profileForm').onsubmit=async e=>{e.preventDefault();const btn=modal.querySelector('button.primary');btn.disabled=true;try{let avatarUrl=modal.querySelector('#pAvatar').value.trim(),coverUrl=modal.querySelector('#pCover').value.trim();const af=modal.querySelector('#pAvatarFile').files?.[0],cf=modal.querySelector('#pCoverFile').files?.[0];if(af)avatarUrl=(await uploadFile(af)).url;if(cf)coverUrl=(await uploadFile(cf)).url;const d=await api('/api/profile/update',{method:'POST',body:JSON.stringify({displayName:modal.querySelector('#pName').value,bio:modal.querySelector('#pBio').value,avatarUrl,coverUrl})});ME=d.user;modal.remove();toast('Profile updated','success');renderShell();}catch(err){toast(err.message,'error')}finally{btn.disabled=false}}; }
  async function peopleModal(username,type){ const modal=openModal(`<div class="modal-title"><div><span class="eyebrow">Community</span><h3>${type==='followers'?'Followers':'Following'}</h3></div><button class="icon-button close">×</button></div><div id="peopleList" class="people-list">${loading()}</div>`);modal.querySelector('.close').onclick=()=>modal.remove();try{const d=await api(`/api/users/${encodeURIComponent(username)}/${type}`);modal.querySelector('#peopleList').innerHTML=d.users.length?d.users.map(u=>`<button class="person-row" data-user="${esc(u.username)}">${avatar(u,'sm')}<div><b>${esc(u.displayName)}</b><small>@${esc(u.username)}</small></div></button>`).join(''):empty('No users yet');modal.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{modal.remove();loadPage('profile',b.dataset.user)})}catch(e){modal.querySelector('#peopleList').innerHTML=empty('Could not load list',e.message)} }

  async function loadMessages(username=''){ const main=$('#main'); try{const d=await api('/api/messages'); const list=d.conversations||[]; if(!username && list[0])username=list[0].user.username; main.innerHTML=`<div class="page-head"><div><span class="eyebrow">Private</span><h1>Messages</h1><p>One-to-one conversations, kept simple.</p></div></div><div class="chat-layout card"><aside class="chat-list"><div class="chat-list-head">Chats <span>${list.length}</span></div><div id="chatList">${list.length?list.map(c=>`<button class="chat-row ${c.user.username===username?'active':''}" data-chat="${esc(c.user.username)}">${avatar(c.user,'sm')}<div><b>${esc(c.user.displayName)}</b><small>${esc(c.lastMessage||'Start a conversation')}</small></div></button>`).join(''):empty('No chats','Open a profile and tap Message.')}</div></aside><section id="chatPane" class="chat-pane">${username?loading('Loading conversation…'):empty('Select a conversation','Choose someone from your messages list.')}</section></div>`;main.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>loadMessages(b.dataset.chat)); if(username)await renderChat(username);}catch(e){main.innerHTML=empty('Messages unavailable',e.message)} }
  async function renderChat(username){const pane=$('#chatPane');const d=await api(`/api/messages/${encodeURIComponent(username)}`);pane.innerHTML=`<div class="chat-head"><button class="icon-button mobile-only" id="backChats">‹</button>${avatar(d.user,'sm')}<div><b>${esc(d.user.displayName)}</b><small>@${esc(d.user.username)}</small></div><button class="icon-button" data-profile="${esc(d.user.username)}">◎</button></div><div id="chatMessages" class="chat-messages">${d.messages.length?d.messages.map(m=>`<div class="msg ${m.senderId===ME.id?'out':'in'}">${m.imageUrl?`<img src="${esc(m.imageUrl)}" alt="">`:''}${m.text?`<div>${esc(m.text)}</div>`:''}<small>${relativeTime(m.createdAt)}</small></div>`).join(''):empty('No messages','Say hello 👋')}</div><form id="chatForm" class="chat-composer"><label class="chat-attach">▧<input type="file" id="chatFile" accept="image/*"></label><input id="chatInput" maxlength="2000" placeholder="Message @${esc(d.user.username)}"><button class="primary">➤</button></form>`; $('#chatMessages').scrollTop=$('#chatMessages').scrollHeight; pane.querySelector('#chatForm').onsubmit=async e=>{e.preventDefault();const input=$('#chatInput'),file=$('#chatFile');if(!input.value.trim()&&!file.files?.[0])return;const btn=e.submitter;btn.disabled=true;try{let imageUrl='';if(file.files?.[0])imageUrl=(await uploadFile(file.files[0])).url;await api(`/api/messages/${encodeURIComponent(username)}`,{method:'POST',body:JSON.stringify({text:input.value.trim(),imageUrl})});input.value='';file.value='';await renderChat(username);}catch(err){toast(err.message,'error')}finally{btn.disabled=false}};pane.querySelector('[data-profile]')?.addEventListener('click',()=>loadPage('profile',username)); }

  async function loadNotifications(){const main=$('#main');main.innerHTML=`<div class="page-head"><div><span class="eyebrow">Activity</span><h1>Notifications</h1><p>Follows, likes, replies and messages.</p></div></div><div id="notificationsList">${loading()}</div>`;try{const d=await api('/api/notifications');$('#notificationsList').innerHTML=d.notifications?.length?d.notifications.map(n=>`<button class="notification-row" data-profile="${esc(n.actor?.username||'')}">${avatar(n.actor,'sm')}<div><p>${esc(n.text)}</p><small>${relativeTime(n.createdAt)}</small></div><span>${n.type==='follow'?'＋':n.type==='like'?'♥':n.type==='comment'?'💬':'✉'}</span></button>`).join(''):empty('All quiet','You’re caught up.');$('#notificationsList').querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>loadPage('profile',b.dataset.profile));await api('/api/notifications/read',{method:'POST'});checkNotifications();}catch(e){$('#notificationsList').innerHTML=empty('Could not load notifications',e.message)} }
  async function loadBookmarks(){const main=$('#main');main.innerHTML=`<div class="page-head"><div><span class="eyebrow">Saved</span><h1>Bookmarks</h1><p>Your saved posts in one place.</p></div></div><div id="feed">${loading()}</div>`;try{const d=await api('/api/bookmarks');renderPosts(d.posts||[],'feed')}catch(e){$('#feed').innerHTML=empty('Could not load bookmarks',e.message)} }

  async function loadSuggestions(){try{const d=await api('/api/suggestions');const box=$('#suggestions');box.innerHTML=d.users.length?d.users.map(u=>`<div class="suggest-row">${avatar(u,'sm')}<button class="person-link" data-profile="${esc(u.username)}"><b>${esc(u.displayName)}</b><small>@${esc(u.username)}</small></button><button class="mini-follow" data-follow="${esc(u.username)}">Follow</button></div>`).join(''):empty('You’re all caught up');box.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>loadPage('profile',b.dataset.profile));box.querySelectorAll('[data-follow]').forEach(b=>b.onclick=async()=>{try{await api(`/api/users/${encodeURIComponent(b.dataset.follow)}/follow`,{method:'POST'});b.textContent='Following';b.disabled=true;}catch(e){toast(e.message,'error')}});}catch(e){$('#suggestions').innerHTML=empty('Suggestions unavailable',e.message)}}
  async function loadTrends(){try{const d=await api('/api/trending');$('#trends').innerHTML=d.trends?.length?d.trends.map(t=>`<button class="trend-row"><span class="trend-tag">${esc(t.tag)}</span><small>${t.count} ${t.count===1?'post':'posts'}</small></button>`).join(''):empty('No trends yet','Use hashtags to start one.');}catch(e){$('#trends').innerHTML=empty('Trends unavailable',e.message)}}
  async function checkNotifications(){try{const d=await api('/api/notifications?unread=1');const n=Number(d.unread||0);$('#notifBadge')?.classList.toggle('hidden',n===0);const b=$('#navNotifBadge');if(b){b.classList.toggle('hidden',n===0);b.textContent=n>9?'9+':n}}catch{}}
  async function runSearch(){const q=$('#globalSearch')?.value.trim();const box=$('#searchResults');if(!q){box?.classList.add('hidden');return}try{const d=await api(`/api/users/search?q=${encodeURIComponent(q.replace(/^@/,''))}`);box.innerHTML=d.users.length?d.users.map(u=>`<button class="search-row" data-profile="${esc(u.username)}">${avatar(u,'sm')}<div><b>${esc(u.displayName)}</b><small>@${esc(u.username)}</small></div></button>`).join(''):empty('No matches');box.classList.remove('hidden');box.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{box.classList.add('hidden');$('#globalSearch').value='';loadPage('profile',b.dataset.profile)});}catch(e){toast(e.message,'error')}}
  async function logout(){try{await api('/api/auth/logout',{method:'POST'});location.reload();}catch(e){toast(e.message,'error')}}

  window.addEventListener('error', e => { if(!ME && !document.querySelector('.auth-screen')) renderAuth(); else if(e?.error && app && !app.innerHTML.trim()) app.innerHTML=empty('Something went wrong','Please refresh and try again.'); });
  init();
})();
