const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let ME=null, state={page:'home',profileUser:null,profileTab:'posts',chatUser:null,searchTimer:null,chatTimer:null};
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,2600)}
async function api(url,opt={}){const o={credentials:'same-origin',...opt,headers:{...(opt.body && !(opt.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(opt.headers||{})}};const r=await fetch(url,o);const d=await r.json().catch(()=>({error:`Request failed (${r.status})`}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
function avatar(u,cls=''){const name=(u?.displayName||u?.username||'?').slice(0,1).toUpperCase();return `<span class="avatar ${cls}">${u?.avatarUrl?`<img src="${esc(u.avatarUrl)}" alt="">`:esc(name)}</span>`}
function when(v){if(!v)return 'now';const sec=v.seconds??v._seconds??Math.floor(new Date(v).getTime()/1000);const d=Math.max(0,Math.floor(Date.now()/1000)-sec);if(d<60)return 'just now';if(d<3600)return `${Math.floor(d/60)}m`;if(d<86400)return `${Math.floor(d/3600)}h`;if(d<604800)return `${Math.floor(d/86400)}d`;return new Date(sec*1000).toLocaleDateString()}
async function init(){try{const d=await api('/api/auth/me');if(d.user){ME=d.user;showApp();await loadHome()}else showAuth()}catch(e){showAuth()}}
function showAuth(){document.body.classList.remove('app-ready');$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden')}
function showApp(){document.body.classList.add('app-ready');$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#miniAvatar').outerHTML=avatar(ME,'avatar-sm');document.querySelector('.profile-mini .avatar').id='miniAvatar';$('#miniName').textContent='@'+ME.username;$('#composerAvatar').outerHTML=avatar(ME);document.querySelector('.composer-top .avatar').id='composerAvatar';setActive('home');loadSuggestions();loadTrends();checkNotifications()}
function setActive(page){$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('.mobile-nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('.page').forEach(p=>p.classList.add('hidden'));$(`#page${page[0].toUpperCase()+page.slice(1)}`)?.classList.remove('hidden');state.page=page}
function nav(page){if(page==='home')loadHome();else if(page==='explore')loadExplore();else if(page==='notifications')loadNotifications();else if(page==='bookmarks')loadBookmarks();else if(page==='profile')loadProfile(ME.username);else if(page==='messages')loadMessages();setActive(page)}
function postHTML(p){const a=p.author||{};return `<article class="post-card card" data-post="${esc(p.id)}"><div class="post-head">${avatar(a)}<div class="post-meta"><strong>${esc(a.displayName||a.username||'User')} ${a.verified?'✓':''}</strong><div class="muted">@${esc(a.username||'user')} · ${when(p.createdAt)}</div></div></div>${p.text?`<div class="post-body">${esc(p.text)}</div>`:''}${p.imageUrl?`<div class="post-image"><img src="${esc(p.imageUrl)}" alt="Post image" loading="lazy"></div>`:''}<div class="post-actions"><button class="action-btn ${p.liked?'liked':''}" data-like="${esc(p.id)}">${p.liked?'♥':'♡'} ${p.likesCount||0}</button><button class="action-btn" data-comments="${esc(p.id)}">💬 ${p.commentsCount||0}</button><button class="action-btn ${p.bookmarked?'saved':''}" data-bookmark="${esc(p.id)}">🔖</button><button class="action-btn" data-share="${esc(p.id)}">↗</button></div></article>`}
function bindPostActions(root){root.querySelectorAll('[data-like]').forEach(b=>b.onclick=async()=>{try{const d=await api(`/api/posts/${b.dataset.like}/like`,{method:'POST'});b.classList.toggle('liked',d.liked);b.innerHTML=`${d.liked?'♥':'♡'} ${d.likesCount||0}`}catch(e){toast(e.message)}});root.querySelectorAll('[data-bookmark]').forEach(b=>b.onclick=async()=>{try{const d=await api(`/api/posts/${b.dataset.bookmark}/bookmark`,{method:'POST'});b.classList.toggle('saved',d.bookmarked)}catch(e){toast(e.message)}});root.querySelectorAll('[data-comments]').forEach(b=>b.onclick=()=>openComments(b.dataset.comments));root.querySelectorAll('[data-share]').forEach(b=>b.onclick=async()=>{const u=location.origin+location.pathname+'?post='+encodeURIComponent(b.dataset.share);try{await navigator.clipboard.writeText(u);toast('Post link copied')}catch{toast(u)}})}
function renderPosts(target,posts){const el=$(target);if(!posts.length){el.innerHTML='<div class="empty">No posts yet. Be the first to share something.</div>';return}el.innerHTML=posts.map(postHTML).join('');bindPostActions(el)}
async function loadHome(){setActive('home');const f=$('#feedList');f.innerHTML='<div class="empty">Loading your feed…</div>';try{renderPosts('#feedList',(await api('/api/feed')).posts||[])}catch(e){f.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function loadExplore(){setActive('explore');const f=$('#exploreList');f.innerHTML='<div class="empty">Loading explore…</div>';try{renderPosts('#exploreList',(await api('/api/explore')).posts||[])}catch(e){f.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function loadBookmarks(){setActive('bookmarks');const f=$('#bookmarksList');f.innerHTML='<div class="empty">Loading bookmarks…</div>';try{renderPosts('#bookmarksList',(await api('/api/bookmarks')).posts||[])}catch(e){f.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function loadNotifications(){setActive('notifications');const n=$('#notificationsList');n.innerHTML='<div class="empty">Loading notifications…</div>';try{const d=await api('/api/notifications');if(!d.notifications?.length){n.innerHTML='<div class="empty">You’re all caught up.</div>';return}n.innerHTML=d.notifications.map(x=>`<div class="notification-row ${x.read?'':'unread'}">${avatar(x.actor,'avatar-sm')}<div><strong>${esc(x.actor?.displayName||'Someone')}</strong><span>${esc(x.text||'')}</span><div class="muted">${when(x.createdAt)}</div></div></div>`).join('');}catch(e){n.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function loadSuggestions(){try{const d=await api('/api/suggestions');const el=$('#suggestions');el.innerHTML=(d.users||[]).map(u=>`<div class="suggest-user">${avatar(u,'avatar-sm')}<div class="suggest-copy"><strong>${esc(u.displayName)}</strong><span class="muted">@${esc(u.username)}</span></div><button class="suggest-btn" data-follow-suggest="${esc(u.username)}">Follow</button></div>`).join('')||'<div class="muted">No suggestions yet.</div>';el.querySelectorAll('[data-follow-suggest]').forEach(b=>b.onclick=async()=>{try{const d=await api(`/api/users/${encodeURIComponent(b.dataset.followSuggest)}/follow`,{method:'POST'});b.textContent=d.following?'Following':'Follow';if(d.following)b.disabled=true}catch(e){toast(e.message)}})}catch(e){$('#suggestions').innerHTML='<div class="muted">Unable to load suggestions.</div>'}}
async function loadTrends(){try{const d=await api('/api/trending');$('#trends').innerHTML=(d.trends||[]).map((t,i)=>`<div class="trend-row"><div class="muted">${i+1} · Trending</div><strong>${esc(t.tag)}</strong><div class="muted">${t.count} posts</div></div>`).join('')||'<div class="muted">No trends yet.</div>'}catch(e){}}
async function checkNotifications(){try{const d=await api('/api/notifications?unread=1');$('#notifDot').classList.toggle('hidden',!(d.count>0))}catch(e){}}
function bindComposer(){const tx=$('#postText'),file=$('#postFile');tx.oninput=()=>$('#charCount').textContent=`${tx.value.length}/1000`;file.onchange=()=>{const f=file.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('#composePreview').innerHTML=`<img src="${r.result}" alt="Preview">`;$('#composePreview').classList.remove('hidden')};r.readAsDataURL(f)};$('#publishPost').onclick=async()=>{const btn=$('#publishPost');const text=tx.value.trim(),f=file.files?.[0];if(!text&&!f)return toast('Write something or add a photo.');btn.disabled=true;try{let imageUrl='';if(f)imageUrl=(await upload(f)).url;await api('/api/posts',{method:'POST',body:JSON.stringify({text,imageUrl})});tx.value='';file.value='';$('#composePreview').classList.add('hidden');$('#charCount').textContent='0/1000';toast('Posted ✨');await loadHome()}catch(e){toast(e.message)}finally{btn.disabled=false}}}
function upload(file){return new Promise((resolve,reject)=>{if(file.size>7*1024*1024)return reject(Error('Image must be under 7 MB.'));const r=new FileReader();r.onload=()=>api('/api/media/upload',{method:'POST',body:JSON.stringify({data:r.result})}).then(resolve).catch(reject);r.onerror=()=>reject(Error('Could not read image.'));r.readAsDataURL(file)})}
async function loadProfile(username){setActive('profile');state.profileUser=username;state.profileTab='posts';$$('.tab').forEach((b,i)=>b.classList.toggle('active',i===0));try{const [u,p]=await Promise.all([api(`/api/users/${encodeURIComponent(username)}`),api(`/api/users/${encodeURIComponent(username)}/posts`)]);$('#profileCard').innerHTML=profileHTML(u.user,u.following);renderPosts('#profileBody',p.posts||[]);bindProfileCard(u.user,u.following)}catch(e){$('#profileCard').innerHTML=`<div class="empty">${esc(e.message)}</div>`;$('#profileBody').innerHTML=''}}
function profileHTML(u,following){return `<div class="profile-cover" style="background-image:${u.coverUrl?`url(${esc(u.coverUrl)})`:''};background-size:cover;background-position:center"></div><div class="profile-inner"><div class="profile-top"><div>${avatar(u,'profile-big-avatar')}</div><div class="profile-actions">${u.id===ME.id?'<button id="editProfile" class="btn btn-ghost">Edit profile</button>':`<button id="followProfile" class="btn ${following?'btn-ghost':'btn-primary'}">${following?'Following':'Follow'}</button>`}</div></div><h2>${esc(u.displayName)} ${u.verified?'✓':''}</h2><div class="profile-handle">@${esc(u.username)}</div>${u.bio?`<p class="profile-bio">${esc(u.bio)}</p>`:''}<div class="profile-stats"><button id="followersBtn"><strong>${u.followersCount||0}</strong><span class="muted">Followers</span></button><button id="followingBtn"><strong>${u.followingCount||0}</strong><span class="muted">Following</span></button></div></div>`}
function bindProfileCard(u,following){$('#editProfile')?.addEventListener('click',()=>openEditProfile(u));$('#followProfile')?.addEventListener('click',async()=>{try{const d=await api(`/api/users/${encodeURIComponent(u.username)}/follow`,{method:'POST'});await loadProfile(u.username)}catch(e){toast(e.message)}});$('#followersBtn')?.addEventListener('click',()=>showPeople('followers'));$('#followingBtn')?.addEventListener('click',()=>showPeople('following'));}
async function loadProfileTab(tab){state.profileTab=tab;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.profileTab===tab));const body=$('#profileBody');body.innerHTML='<div class="empty">Loading…</div>';if(tab==='posts'){const d=await api(`/api/users/${encodeURIComponent(state.profileUser)}/posts`);renderPosts('#profileBody',d.posts||[])}else{const d=await api(`/api/users/${encodeURIComponent(state.profileUser)}/${tab}`);body.innerHTML=(d.users||[]).map(u=>userRow(u)).join('')||'<div class="empty">Nothing here yet.</div>';bindUserRows(body)}}
function userRow(u){return `<div class="user-row">${avatar(u,'avatar-sm')}<div class="user-row-main"><strong>${esc(u.displayName)}</strong><span class="muted">@${esc(u.username)}</span></div><button class="btn btn-ghost" data-open-user="${esc(u.username)}">View</button></div>`}
function bindUserRows(root){root.querySelectorAll('[data-open-user]').forEach(b=>b.onclick=()=>loadProfile(b.dataset.openUser))}
async function showPeople(type){loadProfileTab(type)}
function openEditProfile(u){openModal(`<div class="modal-head"><h3>Edit profile</h3><button id="closeModal" class="icon-btn">✕</button></div><div class="field"><label>Display name</label><input id="editDisplay" value="${esc(u.displayName)}"></div><div class="field"><label>Bio</label><textarea id="editBio" maxlength="280" rows="4">${esc(u.bio||'')}</textarea></div><div class="field"><label>Avatar URL (ImgBB)</label><input id="editAvatar" value="${esc(u.avatarUrl||'')}"></div><button id="saveProfile" class="btn btn-primary btn-wide">Save changes</button>`);$('#saveProfile').onclick=async()=>{try{const d=await api('/api/profile/update',{method:'POST',body:JSON.stringify({displayName:$('#editDisplay').value,bio:$('#editBio').value,avatarUrl:$('#editAvatar').value})});ME=d.user;closeModal();showApp();await loadProfile(ME.username);toast('Profile updated')}catch(e){toast(e.message)}}}
function openModal(content){$('#modal').innerHTML=`<div class="modal">${content}</div>`;$('#modal').classList.remove('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#closeModal')?.addEventListener('click',closeModal)}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').innerHTML=''}
async function openComments(id){openModal(`<div class="modal-head"><h3>Comments</h3><button id="closeModal" class="icon-btn">✕</button></div><div id="commentsBox" class="stack" style="margin:14px 0"><div class="empty">Loading…</div></div><div style="display:flex;gap:8px"><input id="commentText" class="search-input" style="border-radius:12px;background:#fff" placeholder="Write a comment"><button id="sendComment" class="btn btn-primary">Send</button></div>`);try{const d=await api(`/api/posts/${encodeURIComponent(id)}/comments`);$('#commentsBox').innerHTML=(d.comments||[]).map(c=>`<div class="notification-row">${avatar(c.author,'avatar-sm')}<div><strong>${esc(c.author?.displayName||'User')}</strong><div>${esc(c.text)}</div><div class="muted">${when(c.createdAt)}</div></div></div>`).join('')||'<div class="empty">No comments yet.</div>'}catch(e){$('#commentsBox').innerHTML=`<div class="empty">${esc(e.message)}</div>`}$('#sendComment').onclick=async()=>{try{await api(`/api/posts/${encodeURIComponent(id)}/comments`,{method:'POST',body:JSON.stringify({text:$('#commentText').value})});closeModal();openComments(id)}catch(e){toast(e.message)}}}
async function loadMessages(){setActive('messages');$('#messagesListView').classList.remove('hidden');$('#chatView').classList.add('hidden');const list=$('#conversationList');list.innerHTML='<div class="empty">Loading conversations…</div>';try{const d=await api('/api/messages');list.innerHTML=(d.conversations||[]).map(c=>`<button class="conversation" data-chat="${esc(c.user.username)}">${avatar(c.user,'avatar-sm')}<div class="conversation-main"><strong>${esc(c.user.displayName)}</strong><span class="muted">${esc(c.lastMessage||'Start a chat')}</span></div><span class="muted">${when(c.updatedAt)}</span></button>`).join('')||'<div class="empty">No chats yet. Open someone’s profile to message them.</div>';list.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>openChat(b.dataset.chat))}catch(e){list.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function openChat(username){state.chatUser=username;$('#messagesListView').classList.add('hidden');$('#chatView').classList.remove('hidden');try{const d=await api(`/api/messages/${encodeURIComponent(username)}`);$('#chatAvatar').outerHTML=avatar(d.user,'avatar-sm');document.querySelector('.chat-head .avatar').id='chatAvatar';$('#chatName').textContent=d.user.displayName;$('#chatUsername').textContent='@'+d.user.username;renderMessages(d.messages||[]);clearInterval(state.chatTimer);state.chatTimer=setInterval(()=>refreshChat(username),5000)}catch(e){toast(e.message)}}
function renderMessages(rows){const box=$('#chatMessages');box.innerHTML=rows.map(m=>`<div class="bubble ${m.senderId===ME.id?'me':''}">${m.imageUrl?`<img src="${esc(m.imageUrl)}" alt="Photo">`:''}${m.text?`<div>${esc(m.text)}</div>`:''}<div class="muted" style="margin-top:5px;opacity:.75">${when(m.createdAt)}</div></div>`).join('')||'<div class="empty" style="margin:auto">No messages yet.</div>';box.scrollTop=box.scrollHeight}
async function refreshChat(username){try{const d=await api(`/api/messages/${encodeURIComponent(username)}`);renderMessages(d.messages||[])}catch(e){}}
async function sendMessage(){const text=$('#chatText').value.trim(),f=$('#chatFile').files?.[0];if(!text&&!f)return;try{let imageUrl='';if(f)imageUrl=(await upload(f)).url;await api(`/api/messages/${encodeURIComponent(state.chatUser)}`,{method:'POST',body:JSON.stringify({text,imageUrl})});$('#chatText').value='';$('#chatFile').value='';await refreshChat(state.chatUser)}catch(e){toast(e.message)}}
async function runSearch(){const q=$('#globalSearch').value.trim();const box=$('#searchResults');if(!q){box.classList.add('hidden');return}try{const d=await api('/api/search?q='+encodeURIComponent(q));box.innerHTML=(d.users||[]).map(u=>`<button class="search-item" data-search-user="${esc(u.username)}">${avatar(u,'avatar-sm')}<span><strong>${esc(u.displayName)}</strong><div class="muted">@${esc(u.username)}</div></span></button>`).join('')||'<div class="muted" style="padding:10px">No people found.</div>';box.classList.remove('hidden');box.querySelectorAll('[data-search-user]').forEach(b=>b.onclick=()=>{box.classList.add('hidden');$('#globalSearch').value='';loadProfile(b.dataset.searchUser)})}catch(e){box.classList.add('hidden')}}
function startAuth(){let login=true;const sync=()=>{login=!login;$('#authTitle').textContent=login?'Welcome back.':'Create your account.';$('#authSub').textContent=login?'Log in with your email and password.':'Pick a username and join the conversation.';$('#displayField').classList.toggle('hidden',login);$('#usernameField').classList.toggle('hidden',login);$('#displayName').required=!login;$('#username').required=!login;$('#authBtn').textContent=login?'Log in':'Sign up';$('#switchText').textContent=login?'New here?':'Already have an account?';$('#switchAuth').textContent=login?'Create account':'Log in';$('#password').autocomplete=login?'current-password':'new-password'};$('#switchAuth').onclick=sync;$('#authForm').onsubmit=async e=>{e.preventDefault();const btn=$('#authBtn');btn.disabled=true;const payload={email:$('#email').value.trim(),username:$('#username').value.trim(),displayName:$('#displayName').value.trim(),password:$('#password').value};try{const d=await api(login?'/api/auth/login':'/api/auth/register',{method:'POST',body:JSON.stringify(payload)});ME=d.user;showApp();await loadHome()}catch(err){toast(err.message)}finally{btn.disabled=false}}}
function bindGlobal(){bindComposer();$$('[data-page]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));$('#createPostSide').onclick=()=>{$('#postText').focus();window.scrollTo({top:120,behavior:'smooth'})};$('#mobileCreate').onclick=()=>{$('#postText').focus();window.scrollTo({top:120,behavior:'smooth'})};$('#logoutBtn').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()};$('#refreshFeed').onclick=loadHome;$('#markNotifications').onclick=async()=>{await api('/api/notifications/read',{method:'POST'});await loadNotifications();checkNotifications()};$('#chatBack').onclick=()=>{clearInterval(state.chatTimer);loadMessages()};$('#sendChat').onclick=sendMessage;$('#chatText').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}};$('#globalSearch').oninput=()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(runSearch,250)};document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('#searchResults').classList.add('hidden')});$$('[data-profile-tab]').forEach(b=>b.onclick=()=>loadProfileTab(b.dataset.profileTab))}
startAuth();bindGlobal();init();
