const express=require('express');const admin=require('firebase-admin');const crypto=require('crypto');const path=require('path');
const app=express();app.use(express.json({limit:'12mb'}));app.use(express.urlencoded({extended:true,limit:'12mb'}));
let db;try{if(!admin.apps.length){const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('FIREBASE_SERVICE_ACCOUNT_JSON is missing');const service=JSON.parse(raw);admin.initializeApp({credential:admin.credential.cert(service),...(process.env.FIREBASE_DATABASE_URL?{databaseURL:process.env.FIREBASE_DATABASE_URL}:{})});}db=admin.firestore()}catch(e){console.error('Firebase init:',e.message)}
const FV=admin.firestore.FieldValue, now=()=>admin.firestore.Timestamp.now();const clean=(v,n=1000)=>String(v??'').trim().slice(0,n);const uname=v=>clean(v,24).toLowerCase().replace(/[^a-z0-9_]/g,'');
const hash=(p,s=crypto.randomBytes(16).toString('hex'))=>`${s}:${crypto.scryptSync(p,s,64).toString('hex')}`;const verify=(p,st)=>{try{const [s,d]=st.split(':');const a=Buffer.from(d,'hex'),b=crypto.scryptSync(p,s,64);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}};
const secret=()=>process.env.SESSION_SECRET||'CHANGE_ME_BLUEWAVE_SESSION_SECRET';const sign=id=>{const body=Buffer.from(JSON.stringify({id,exp:Date.now()+2592e6})).toString('base64url');const sig=crypto.createHmac('sha256',secret()).update(body).digest('base64url');return `${body}.${sig}`};
const unsign=t=>{try{const [b,s]=String(t||'').split('.'),g=crypto.createHmac('sha256',secret()).update(b).digest('base64url');if(!b||!s||s.length!==g.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(g)))return null;const x=JSON.parse(Buffer.from(b,'base64url').toString());return x.exp>Date.now()?x.id:null}catch{return null}};
const cookie=(res,n,v,max=2592000)=>res.setHeader('Set-Cookie',`${n}=${encodeURIComponent(v)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${max}; Secure`);const getCookie=(req,n)=>{const m=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(n+'='));return m?decodeURIComponent(m.slice(n.length+1)):''};
async function userById(id){if(!db)return null;const s=await db.collection('users').doc(id).get();return s.exists?{id:s.id,...s.data()}:null}function safe(u){return u?{id:u.id,username:u.username,displayName:u.displayName||u.username,bio:u.bio||'',avatarUrl:u.avatarUrl||'',coverUrl:u.coverUrl||'',followersCount:u.followersCount||0,followingCount:u.followingCount||0,postsCount:u.postsCount||0,isVerified:!!u.isVerified,isAdmin:!!u.isAdmin,createdAt:u.createdAt||null}:null}
async function current(req){const id=unsign(getCookie(req,'bw_session'));return id?userById(id):null}async function auth(req,res,next){try{if(!db)return res.status(503).json({error:'Firebase is not configured.'});const u=await current(req);if(!u)return res.status(401).json({error:'Please log in.'});req.user=u;next()}catch(e){res.status(500).json({error:'Authentication failed.'})}}
const notify=async(userId,actorId,type,text,postId='')=>{if(userId&&userId!==actorId)await db.collection('notifications').add({userId,actorId,type,text,postId,read:false,createdAt:now()})};
async function attachPosts(docs,viewer){const out=[];for(const d of docs){const p={id:d.id,...d.data()},u=await userById(p.authorId);const [l,s]=await Promise.all([db.collection('postLikes').doc(`${p.id}_${viewer}`).get(),db.collection('bookmarks').doc(`${viewer}_${p.id}`).get()]);out.push({...p,author:safe(u),liked:l.exists,bookmarked:s.exists})}return out}
const ts=x=>x?.createdAt?.seconds||x?.createdAt?._seconds||0;
app.get('/api/health',(q,r)=>r.json({ok:true,service:'bluewave',firebase:!!db,imgbb:!!process.env.IMGBB_API_KEY}));
app.get('/api/auth/me',async(q,r)=>{try{r.json({user:safe(await current(q))})}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/auth/register',async(req,res)=>{try{if(!db)throw Error('Firebase is not configured.');const u=uname(req.body.username),displayName=clean(req.body.displayName,40)||u,p=String(req.body.password||'');if(u.length<3)throw Error('Username must be at least 3 characters.');if(p.length<6)throw Error('Password must be at least 6 characters.');const ref=db.collection('users').doc(u);if((await ref.get()).exists)throw Error('Username is already taken.');const x={username:u,displayName,bio:'',avatarUrl:'',coverUrl:'',passwordHash:hash(p),followersCount:0,followingCount:0,postsCount:0,isVerified:false,isAdmin:process.env.ADMIN_USERNAME===u,createdAt:now()};await ref.set(x);cookie(res,'bw_session',sign(u));res.json({ok:true,user:safe({id:u,...x})})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const u=await userById(uname(req.body.username)),p=String(req.body.password||'');if(!u||!verify(p,u.passwordHash))throw Error('Invalid username or password.');cookie(res,'bw_session',sign(u.id));res.json({ok:true,user:safe(u)})}catch(e){res.status(401).json({error:e.message})}});
app.post('/api/auth/logout',(q,r)=>{cookie(r,'bw_session','',0);r.json({ok:true})});app.post('/api/auth/password',auth,async(req,res)=>{try{if(!verify(String(req.body.oldPassword||''),req.user.passwordHash))throw Error('Current password is incorrect.');const p=String(req.body.newPassword||'');if(p.length<6)throw Error('New password must be at least 6 characters.');await db.collection('users').doc(req.user.id).update({passwordHash:hash(p)});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/media/upload',auth,async(req,res)=>{try{if(!process.env.IMGBB_API_KEY)throw Error('IMGBB_API_KEY is not configured.');const data=String(req.body.data||'');if(!/^data:image\//.test(data))throw Error('Please upload an image.');const form=new URLSearchParams({key:process.env.IMGBB_API_KEY,image:data.split(',')[1]});const rr=await fetch('https://api.imgbb.com/1/upload',{method:'POST',body:form});const d=await rr.json();if(!rr.ok||!d.success)throw Error(d?.error?.message||'ImgBB upload failed.');res.json({ok:true,url:d.data.url,deleteUrl:d.data.delete_url||''})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/feed',auth,async(req,res)=>{try{const f=await db.collection('follows').where('followerId','==',req.user.id).get(),ids=[req.user.id,...f.docs.map(d=>d.data().followingId)],docs=[];for(let i=0;i<ids.length;i+=10){const s=await db.collection('posts').where('authorId','in',ids.slice(i,i+10)).limit(50).get();docs.push(...s.docs)}docs.sort((a,b)=>ts(b.data())-ts(a.data()));res.json({posts:await attachPosts(docs.slice(0,80),req.user.id)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/explore',auth,async(req,res)=>{try{const s=await db.collection('posts').limit(100).get();s.docs.sort((a,b)=>ts(b.data())-ts(a.data()));res.json({posts:await attachPosts(s.docs.slice(0,60),req.user.id)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/posts',auth,async(req,res)=>{try{const text=clean(req.body.text,1000),imageUrl=clean(req.body.imageUrl,1200);if(!text&&!imageUrl)throw Error('Write something or add a photo.');const ref=await db.collection('posts').add({authorId:req.user.id,text,imageUrl,likesCount:0,commentsCount:0,createdAt:now()});await db.collection('users').doc(req.user.id).update({postsCount:FV.increment(1)});res.json({ok:true,id:ref.id})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/posts/:id',auth,async(req,res)=>{try{const ref=db.collection('posts').doc(req.params.id),s=await ref.get();if(!s.exists)throw Error('Post not found.');if(s.data().authorId!==req.user.id&&!req.user.isAdmin)throw Error('Not allowed.');await ref.delete();await db.collection('users').doc(s.data().authorId).update({postsCount:FV.increment(-1)});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/posts/:id/like',auth,async(req,res)=>{try{const p=await db.collection('posts').doc(req.params.id).get();if(!p.exists)throw Error('Post not found.');const ref=db.collection('postLikes').doc(`${req.params.id}_${req.user.id}`),s=await ref.get();let liked;if(s.exists){await ref.delete();await p.ref.update({likesCount:FV.increment(-1)});liked=false}else{await ref.set({postId:req.params.id,userId:req.user.id,createdAt:now()});await p.ref.update({likesCount:FV.increment(1)});liked=true;await notify(p.data().authorId,req.user.id,'like',`${req.user.displayName} liked your post`,req.params.id)}const fresh=await p.ref.get();res.json({liked,likesCount:fresh.data().likesCount||0})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/posts/:id/comments',auth,async(req,res)=>{try{const s=await db.collection('comments').where('postId','==',req.params.id).limit(100).get(),a=[];for(const d of s.docs){const x=d.data();a.push({...x,id:d.id,author:safe(await userById(x.userId))})}a.sort((x,y)=>ts(x)-ts(y));res.json({comments:a})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/posts/:id/comments',auth,async(req,res)=>{try{const text=clean(req.body.text,500),p=await db.collection('posts').doc(req.params.id).get();if(!text)throw Error('Comment is empty.');if(!p.exists)throw Error('Post not found.');await db.collection('comments').add({postId:req.params.id,userId:req.user.id,text,createdAt:now()});await p.ref.update({commentsCount:FV.increment(1)});await notify(p.data().authorId,req.user.id,'comment',`${req.user.displayName} replied to your post`,req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/posts/:id/bookmark',auth,async(req,res)=>{try{const ref=db.collection('bookmarks').doc(`${req.user.id}_${req.params.id}`),s=await ref.get();if(s.exists)await ref.delete();else await ref.set({userId:req.user.id,postId:req.params.id,createdAt:now()});res.json({bookmarked:!s.exists})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/bookmarks',auth,async(req,res)=>{try{const s=await db.collection('bookmarks').where('userId','==',req.user.id).limit(80).get(),docs=[];for(const d of s.docs){const p=await db.collection('posts').doc(d.data().postId).get();if(p.exists)docs.push(p)}docs.sort((a,b)=>ts(b.data())-ts(a.data()));res.json({posts:await attachPosts(docs,req.user.id)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/search',auth,async(req,res)=>{try{const q=uname(req.query.q);if(!q)return res.json({users:[]});const s=await db.collection('users').orderBy('username').startAt(q).endAt(q+'\uf8ff').limit(20).get();res.json({users:s.docs.map(d=>safe({id:d.id,...d.data()}))})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/suggestions',auth,async(req,res)=>{try{const f=await db.collection('follows').where('followerId','==',req.user.id).get(),ex=new Set([req.user.id,...f.docs.map(d=>d.data().followingId)]),s=await db.collection('users').limit(50).get();res.json({users:s.docs.map(d=>safe({id:d.id,...d.data()})).filter(u=>!ex.has(u.id)).slice(0,8)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/users/:username',auth,async(req,res)=>{try{const id=uname(req.params.username),u=await userById(id);if(!u)throw Error('User not found.');const f=await db.collection('follows').doc(`${req.user.id}_${id}`).get();res.json({user:safe(u),following:f.exists})}catch(e){res.status(404).json({error:e.message})}});
app.patch('/api/users/me',auth,async(req,res)=>{try{const x={displayName:clean(req.body.displayName,40)||req.user.username,bio:clean(req.body.bio,160),avatarUrl:clean(req.body.avatarUrl,1200),coverUrl:clean(req.body.coverUrl,1200)};await db.collection('users').doc(req.user.id).update(x);res.json({user:safe({...req.user,...x})})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/users/:username/posts',auth,async(req,res)=>{try{const s=await db.collection('posts').where('authorId','==',uname(req.params.username)).limit(100).get();s.docs.sort((a,b)=>ts(b.data())-ts(a.data()));res.json({posts:await attachPosts(s.docs,req.user.id)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/users/:username/follow',auth,async(req,res)=>{try{const target=uname(req.params.username);if(target===req.user.id)throw Error('You cannot follow yourself.');if(!await userById(target))throw Error('User not found.');const ref=db.collection('follows').doc(`${req.user.id}_${target}`),s=await ref.get();if(s.exists){await ref.delete();await db.collection('users').doc(req.user.id).update({followingCount:FV.increment(-1)});await db.collection('users').doc(target).update({followersCount:FV.increment(-1)});res.json({following:false})}else{await ref.set({followerId:req.user.id,followingId:target,createdAt:now()});await db.collection('users').doc(req.user.id).update({followingCount:FV.increment(1)});await db.collection('users').doc(target).update({followersCount:FV.increment(1)});await notify(target,req.user.id,'follow',`${req.user.displayName} started following you`);res.json({following:true})}}catch(e){res.status(400).json({error:e.message})}});
async function people(u,type){const s=await db.collection('follows').where(type==='followers'?'followingId':'followerId','==',u).limit(100).get(),out=[];for(const d of s.docs){const id=type==='followers'?d.data().followerId:d.data().followingId, x=await userById(id);if(x)out.push(safe(x))}return out}
app.get('/api/users/:username/followers',auth,async(req,res)=>{try{res.json({users:await people(uname(req.params.username),'followers')})}catch(e){res.status(500).json({error:e.message})}});app.get('/api/users/:username/following',auth,async(req,res)=>{try{res.json({users:await people(uname(req.params.username),'following')})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/trending',auth,async(req,res)=>{try{const s=await db.collection('posts').limit(150).get(),c={};for(const d of s.docs)for(const t of String(d.data().text||'').match(/#[a-z0-9_]+/gi)||[]){const k=t.toLowerCase();c[k]=(c[k]||0)+1}res.json({trends:Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([tag,count])=>({tag,count}))})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/notifications',auth,async(req,res)=>{try{const s=await db.collection('notifications').where('userId','==',req.user.id).limit(100).get(),a=[];for(const d of s.docs){const x=d.data();a.push({...x,id:d.id,actor:safe(await userById(x.actorId))})}a.sort((x,y)=>ts(y)-ts(x));res.json({notifications:a,count:a.filter(x=>!x.read).length})}catch(e){res.status(500).json({error:e.message})}});app.post('/api/notifications/read',auth,async(req,res)=>{try{const s=await db.collection('notifications').where('userId','==',req.user.id).where('read','==',false).limit(100).get();await Promise.all(s.docs.map(d=>d.ref.update({read:true})));res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
const cid=(a,b)=>[a,b].sort().join('__');app.get('/api/messages',auth,async(req,res)=>{try{const s=await db.collection('conversations').where('participants','array-contains',req.user.id).limit(50).get(),a=[];for(const d of s.docs){const x=d.data(),other=x.participants.find(p=>p!==req.user.id),u=await userById(other);if(u)a.push({id:d.id,lastMessage:x.lastMessage||'',updatedAt:x.updatedAt,user:safe(u)})}a.sort((x,y)=>ts(y)-ts(x));res.json({conversations:a})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/messages/:username',auth,async(req,res)=>{try{const u=await userById(uname(req.params.username));if(!u)throw Error('User not found.');const c=await db.collection('conversations').doc(cid(req.user.id,u.id)).get();if(!c.exists)return res.json({user:safe(u),messages:[]});const s=await c.ref.collection('messages').limit(150).get(),a=s.docs.map(d=>({id:d.id,...d.data()}));a.sort((x,y)=>ts(x)-ts(y));res.json({user:safe(u),messages:a})}catch(e){res.status(404).json({error:e.message})}});
app.post('/api/messages/:username',auth,async(req,res)=>{try{const u=await userById(uname(req.params.username));if(!u)throw Error('User not found.');const text=clean(req.body.text,2000),imageUrl=clean(req.body.imageUrl,1200);if(!text&&!imageUrl)throw Error('Message is empty.');const ref=db.collection('conversations').doc(cid(req.user.id,u.id));await ref.set({participants:[req.user.id,u.id],lastMessage:text||'📷 Photo',updatedAt:now()},{merge:true});await ref.collection('messages').add({senderId:req.user.id,receiverId:u.id,text,imageUrl,createdAt:now()});await notify(u.id,req.user.id,'message',`${req.user.displayName} sent you a message`);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/admin/stats',auth,async(req,res)=>{if(!req.user.isAdmin)return res.status(403).json({error:'Admin access required.'});try{const [u,p,f,n]=await Promise.all([db.collection('users').get(),db.collection('posts').get(),db.collection('follows').get(),db.collection('notifications').get()]);res.json({users:u.size,posts:p.size,follows:f.size,notifications:n.size})}catch(e){res.status(500).json({error:e.message})}});
app.use(express.static(path.join(__dirname,'..')));app.use((req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'API route not found.'});res.sendFile(path.join(__dirname,'..','index.html'))});module.exports=app;
