const express=require('express'),crypto=require('crypto'),admin=require('firebase-admin');
const app=express();app.use(express.json({limit:'10mb'}));
if(!admin.apps.length){const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('Missing FIREBASE_SERVICE_ACCOUNT_JSON');admin.initializeApp({credential:admin.credential.cert(JSON.parse(raw)),databaseURL:process.env.FIREBASE_DATABASE_URL||undefined});}
const db=admin.firestore(),FV=admin.firestore.FieldValue;
const SECRET=process.env.SESSION_SECRET||'change-me';
const clean=(v,m=1000)=>String(v??'').trim().slice(0,m), username=v=>clean(v,30).toLowerCase().replace(/[^a-z0-9_.-]/g,'');
const uid=()=>crypto.randomBytes(12).toString('hex');
function sign(v){return crypto.createHmac('sha256',SECRET).update(v).digest('hex')}
function cookies(req){const out={};for(const part of (req.headers.cookie||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function setSession(res,id){const exp=Date.now()+30*86400000,body=`${id}.${exp}`;res.setHeader('Set-Cookie',`bw_session=${encodeURIComponent(body+'.'+sign(body))}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000`)}
function currentId(req){const p=(cookies(req).bw_session||'').split('.');if(p.length!==3||!p[0]||Number(p[1])<Date.now()||sign(`${p[0]}.${p[1]}`)!==p[2])return null;return p[0]}
async function getUser(id){if(!id)return null;const s=await db.collection('users').doc(id).get();return s.exists?{id:s.id,...s.data()}:null}
async function me(req){return getUser(currentId(req))}
async function requireUser(req,res,next){try{const u=await me(req);if(!u)return res.status(401).json({error:'Login required.'});req.user=u;next()}catch(e){res.status(500).json({error:e.message})}}
function safe(u){return{id:u.id,username:u.username,email:u.email||'',displayName:u.displayName||u.username,bio:u.bio||'',avatarUrl:u.avatarUrl||'',coverUrl:u.coverUrl||'',verified:!!u.verified,followersCount:u.followersCount||0,followingCount:u.followingCount||0,createdAt:u.createdAt||null}}
function hashPassword(p,salt=crypto.randomBytes(16).toString('hex')){return new Promise((ok,no)=>crypto.scrypt(String(p),salt,64,(e,b)=>e?no(e):ok(`${salt}:${b.toString('hex')}`)))}
function checkPassword(p,stored){return new Promise((ok,no)=>{const [salt,h]=String(stored||'').split(':');if(!salt||!h)return ok(false);crypto.scrypt(String(p),salt,64,(e,b)=>e?no(e):ok(crypto.timingSafeEqual(Buffer.from(h,'hex'),b)))})}
async function imgBB(data){const key=process.env.IMGBB_API_KEY;if(!key)throw Error('IMGBB_API_KEY is not configured.');const raw=String(data).replace(/^data:image\/[^;]+;base64,/i,'').replace(/\s/g,'');const fd=new FormData();fd.append('key',key);fd.append('image',raw);const r=await fetch('https://api.imgbb.com/1/upload',{method:'POST',body:fd});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.error?.message||'Image upload failed.');return d.data.url}
function stamp(){return FV.serverTimestamp()}
async function notify(userId,actorId,type,text,postId=''){if(!userId||userId===actorId)return;await db.collection('notifications').add({userId,actorId,type,text,postId,read:false,createdAt:stamp()})}
async function attachUsers(posts,viewerId){const ids=[...new Set(posts.map(p=>p.authorId).filter(Boolean))];const users={};for(let i=0;i<ids.length;i+=10){const docs=await Promise.all(ids.slice(i,i+10).map(x=>db.collection('users').doc(x).get()));docs.forEach(s=>{if(s.exists)users[s.id]=safe({id:s.id,...s.data()})})}const liked=new Set(),saved=new Set();if(viewerId&&posts.length){const likes=await Promise.all(posts.map(p=>db.collection('postLikes').doc(`${p.id}_${viewerId}`).get()));likes.forEach((s,i)=>{if(s.exists)liked.add(posts[i].id)});const marks=await Promise.all(posts.map(p=>db.collection('bookmarks').doc(`${viewerId}_${p.id}`).get()));marks.forEach((s,i)=>{if(s.exists)saved.add(posts[i].id)})}return posts.map(p=>({...p,author:users[p.authorId]||null,liked:liked.has(p.id),bookmarked:saved.has(p.id)}))}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'BlueWave'}));
app.get('/api/auth/me',async(req,res)=>{try{const u=await me(req);res.json({user:u?safe(u):null})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/register',async(req,res)=>{try{const email=clean(req.body.email,160).toLowerCase(),un=username(req.body.username),pw=String(req.body.password||'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Please enter a valid email address.');if(!/^[a-z0-9_.-]{3,24}$/.test(un))throw Error('Username must be 3–24 characters.');if(pw.length<6)throw Error('Password must be at least 6 characters.');const ref=db.collection('users').doc(un),old=await ref.get();if(old.exists)throw Error('Username already exists.');const emailSnap=await db.collection('users').where('emailLower','==',email).limit(1).get();if(!emailSnap.empty)throw Error('Email is already registered.');const passwordHash=await hashPassword(pw);await ref.set({username:un,email,emailLower:email,displayName:clean(req.body.displayName,60)||un,bio:'',avatarUrl:'',coverUrl:'',passwordHash,followersCount:0,followingCount:0,verified:false,createdAt:stamp()});setSession(res,un);const u=await ref.get();res.json({ok:true,user:safe({id:ref.id,...u.data()})})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const email=clean(req.body.email,160).toLowerCase(),pw=String(req.body.password||'');if(!email||!pw)throw Error('Email and password are required.');const s=await db.collection('users').where('emailLower','==',email).limit(1).get();if(s.empty)throw Error('Invalid email or password.');const doc=s.docs[0],data=doc.data();if(!(await checkPassword(pw,data.passwordHash)))throw Error('Invalid email or password.');setSession(res,doc.id);res.json({ok:true,user:safe({id:doc.id,...data})})}catch(e){res.status(401).json({error:e.message})}});
app.post('/api/admin/login',async(req,res)=>{try{const adminUser=clean(process.env.ADMIN_USERNAME,60).toLowerCase(),adminPass=String(process.env.ADMIN_PASSWORD||''),supplied=clean(req.body.username,60).toLowerCase(),pw=String(req.body.password||'');if(!adminUser||!adminPass||supplied!==adminUser||pw!==adminPass)throw Error('Invalid admin credentials.');setSession(res,adminUser);res.json({ok:true})}catch(e){res.status(401).json({error:e.message})}});
app.post('/api/auth/logout',(req,res)=>{res.setHeader('Set-Cookie','bw_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0');res.json({ok:true})});
app.post('/api/media/upload',requireUser,async(req,res)=>{try{const data=String(req.body.data||'');if(!/^data:image\/(jpeg|jpg|png|webp|gif);base64,/i.test(data))throw Error('Only JPG, PNG, WEBP or GIF images are supported.');if(data.length>9*1024*1024)throw Error('Image is too large.');res.json({ok:true,url:await imgBB(data)})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/profile/update',requireUser,(req,res)=>res.status(405).json({error:'Use POST.'}));
app.post('/api/profile/update',requireUser,async(req,res)=>{try{const data={displayName:clean(req.body.displayName,60)||req.user.username,bio:clean(req.body.bio,280),avatarUrl:clean(req.body.avatarUrl,1000)};await db.collection('users').doc(req.user.id).update(data);const u=await getUser(req.user.id);res.json({ok:true,user:safe(u)})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/feed',requireUser,async(req,res)=>{try{const fs=await db.collection('follows').where('followerId','==',req.user.id).get();const ids=[req.user.id,...fs.docs.map(d=>d.data().followingId)];let rows=[];for(let i=0;i<ids.length;i+=10){const s=await db.collection('posts').where('authorId','in',ids.slice(i,i+10)).limit(100).get();rows.push(...s.docs.map(d=>({id:d.id,...d.data()})))}rows.sort((a,b)=>(b.createdAt?._seconds||0)-(a.createdAt?._seconds||0));res.json({posts:await attachUsers(rows.slice(0,80),req.user.id)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/explore',requireUser,async(req,res)=>{try{const s=await db.collection('posts').limit(120).get();const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?._seconds||0)-(a.createdAt?._seconds||0));res.json({posts:await attachUsers(rows.slice(0,60),req.user.id)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/posts',requireUser,async(req,res)=>{try{const text=clean(req.body.text,1000),imageUrl=clean(req.body.imageUrl,1000);if(!text&&!imageUrl)throw Error('Write something or add a photo.');const ref=db.collection('posts').doc();await ref.set({authorId:req.user.id,text,imageUrl,likesCount:0,commentsCount:0,createdAt:stamp()});res.json({ok:true,id:ref.id})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/posts/:id/like',requireUser,async(req,res)=>{try{const post=await db.collection('posts').doc(req.params.id).get();if(!post.exists)throw Error('Post not found.');const ref=db.collection('postLikes').doc(`${req.params.id}_${req.user.id}`),s=await ref.get();let liked;if(s.exists){await ref.delete();await post.ref.update({likesCount:FV.increment(-1)});liked=false}else{await ref.set({postId:req.params.id,userId:req.user.id,createdAt:stamp()});await post.ref.update({likesCount:FV.increment(1)});liked=true;await notify(post.data().authorId,req.user.id,'like',`${req.user.displayName} liked your post`,req.params.id)}const fresh=await post.ref.get();res.json({ok:true,liked,likesCount:fresh.data().likesCount||0})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/posts/:id/comments',requireUser,async(req,res)=>{try{const s=await db.collection('comments').where('postId','==',req.params.id).limit(100).get();const rows=s.docs.map(d=>({id:d.id,...d.data()}));rows.sort((a,b)=>(a.createdAt?._seconds||0)-(b.createdAt?._seconds||0));const out=[];for(const c of rows){const u=await getUser(c.userId);out.push({...c,author:u?safe(u):null})}res.json({comments:out})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/posts/:id/comments',requireUser,async(req,res)=>{try{const text=clean(req.body.text,500);if(!text)throw Error('Comment is empty.');const p=await db.collection('posts').doc(req.params.id).get();if(!p.exists)throw Error('Post not found.');await db.collection('comments').add({postId:req.params.id,userId:req.user.id,text,createdAt:stamp()});await p.ref.update({commentsCount:FV.increment(1)});await notify(p.data().authorId,req.user.id,'comment',`${req.user.displayName} replied to your post`,req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/posts/:id/bookmark',requireUser,async(req,res)=>{try{const ref=db.collection('bookmarks').doc(`${req.user.id}_${req.params.id}`),s=await ref.get();if(s.exists)await ref.delete();else await ref.set({userId:req.user.id,postId:req.params.id,createdAt:stamp()});res.json({ok:true,bookmarked:!s.exists})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/bookmarks',requireUser,async(req,res)=>{try{const s=await db.collection('bookmarks').where('userId','==',req.user.id).limit(80).get();const ids=s.docs.map(d=>d.data().postId);const rows=[];for(const id of ids){const p=await db.collection('posts').doc(id).get();if(p.exists)rows.push({id:p.id,...p.data()})}rows.sort((a,b)=>(b.createdAt?._seconds||0)-(a.createdAt?._seconds||0));res.json({posts:await attachUsers(rows,req.user.id)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/search',requireUser,async(req,res)=>{try{const q=clean(req.query.q,60).toLowerCase();if(!q)return res.json({users:[]});const s=await db.collection('users').orderBy('username').startAt(q).endAt(q+'\uf8ff').limit(20).get();res.json({users:s.docs.map(d=>safe({id:d.id,...d.data()}))})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/users/search',requireUser,async(req,res)=>{req.url='/api/search?q='+encodeURIComponent(req.query.q||'');return app._router.handle(req,res,()=>{})});
app.get('/api/users/:username',requireUser,async(req,res)=>{try{const s=await db.collection('users').doc(username(req.params.username)).get();if(!s.exists)return res.status(404).json({error:'User not found.'});const u={id:s.id,...s.data()},f=await db.collection('follows').doc(`${req.user.id}_${s.id}`).get();res.json({user:safe(u),following:f.exists})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/users/:username/follow',requireUser,async(req,res)=>{try{const target=username(req.params.username);if(target===req.user.id)throw Error('You cannot follow yourself.');const t=await getUser(target);if(!t)throw Error('User not found.');const ref=db.collection('follows').doc(`${req.user.id}_${target}`),s=await ref.get();if(s.exists){await ref.delete();await db.collection('users').doc(req.user.id).update({followingCount:FV.increment(-1)});await db.collection('users').doc(target).update({followersCount:FV.increment(-1)});res.json({ok:true,following:false})}else{await ref.set({followerId:req.user.id,followingId:target,createdAt:stamp()});await db.collection('users').doc(req.user.id).update({followingCount:FV.increment(1)});await db.collection('users').doc(target).update({followersCount:FV.increment(1)});await notify(target,req.user.id,'follow',`${req.user.displayName} started following you`);res.json({ok:true,following:true})}}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/users/:username/posts',requireUser,async(req,res)=>{try{const s=await db.collection('posts').where('authorId','==',username(req.params.username)).limit(100).get();const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?._seconds||0)-(a.createdAt?._seconds||0));res.json({posts:await attachUsers(rows,req.user.id)})}catch(e){res.status(500).json({error:e.message})}});
async function people(usernameVal,type){const s=await db.collection('follows').where(type==='followers'?'followingId':'followerId','==',usernameVal).limit(100).get();const ids=s.docs.map(d=>type==='followers'?d.data().followerId:d.data().followingId);const out=[];for(const id of ids){const u=await getUser(id);if(u)out.push(safe(u))}return out}
app.get('/api/users/:username/followers',requireUser,async(req,res)=>{try{res.json({users:await people(username(req.params.username),'followers')})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/users/:username/following',requireUser,async(req,res)=>{try{res.json({users:await people(username(req.params.username),'following')})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/suggestions',requireUser,async(req,res)=>{try{const fs=await db.collection('follows').where('followerId','==',req.user.id).get();const excluded=new Set([req.user.id,...fs.docs.map(d=>d.data().followingId)]);const s=await db.collection('users').limit(30).get();res.json({users:s.docs.map(d=>safe({id:d.id,...d.data()})).filter(u=>!excluded.has(u.id)).slice(0,6)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/trending',requireUser,async(req,res)=>{try{const s=await db.collection('posts').limit(150).get(),counts={};for(const d of s.docs){const text=d.data().text||'';for(const t of text.match(/#[a-z0-9_]+/gi)||[]){const tag=t.toLowerCase();counts[tag]=(counts[tag]||0)+1}}const trends=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([tag,count])=>({tag,count}));res.json({trends})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/notifications',requireUser,async(req,res)=>{try{const s=await db.collection('notifications').where('userId','==',req.user.id).limit(80).get();const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?._seconds||0)-(a.createdAt?._seconds||0));const out=[];for(const n of rows){const u=await getUser(n.actorId);out.push({...n,actor:u?safe(u):null})}res.json({notifications:out,count:req.query.unread==='1'?rows.filter(x=>!x.read).length:rows.length})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/notifications/read',requireUser,async(req,res)=>{try{const s=await db.collection('notifications').where('userId','==',req.user.id).where('read','==',false).limit(100).get();await Promise.all(s.docs.map(d=>d.ref.update({read:true})));res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
function chatId(a,b){return [a,b].sort().join('__')}
app.get('/api/messages',requireUser,async(req,res)=>{try{const s=await db.collection('conversations').where('participants','array-contains',req.user.id).limit(50).get();const rows=[];for(const d of s.docs){const x=d.data(),other=x.participants.find(p=>p!==req.user.id),u=await getUser(other);if(u)rows.push({id:d.id,lastMessage:x.lastMessage||'',updatedAt:x.updatedAt,user:safe(u)})}rows.sort((a,b)=>(b.updatedAt?._seconds||0)-(a.updatedAt?._seconds||0));res.json({conversations:rows})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/messages/:username',requireUser,async(req,res)=>{try{const u=await getUser(username(req.params.username));if(!u)return res.status(404).json({error:'User not found.'});const cid=chatId(req.user.id,u.id),c=await db.collection('conversations').doc(cid).get();if(!c.exists)return res.json({user:safe(u),messages:[]});const s=await c.ref.collection('messages').limit(100).get();const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.createdAt?._seconds||0)-(b.createdAt?._seconds||0));res.json({user:safe(u),messages:rows})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/messages/:username',requireUser,async(req,res)=>{try{const u=await getUser(username(req.params.username));if(!u)return res.status(404).json({error:'User not found.'});const text=clean(req.body.text,2000),imageUrl=clean(req.body.imageUrl,1000);if(!text&&!imageUrl)throw Error('Message is empty.');const cid=chatId(req.user.id,u.id),ref=db.collection('conversations').doc(cid);await ref.set({participants:[req.user.id,u.id],lastMessage:text||'📷 Photo',updatedAt:stamp()},{merge:true});await ref.collection('messages').add({senderId:req.user.id,receiverId:u.id,text,imageUrl,createdAt:stamp()});await notify(u.id,req.user.id,'message',`${req.user.displayName} sent you a message`);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/admin/stats',async(req,res)=>{const adminUser=process.env.ADMIN_USERNAME;if(!adminUser||currentId(req)!==adminUser)return res.status(403).json({error:'Admin access required.'});try{const [u,p,f,n]=await Promise.all([db.collection('users').get(),db.collection('posts').get(),db.collection('follows').get(),db.collection('notifications').get()]);res.json({users:u.size,posts:p.size,follows:f.size,notifications:n.size})}catch(e){res.status(500).json({error:e.message})}});
app.use(express.static('.'));
module.exports=app;
