const express=require('express'),crypto=require('crypto'),admin=require('firebase-admin');
const app=express();
app.use(express.json({limit:'8mb'}));
if(!admin.apps.length){const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('Missing FIREBASE_SERVICE_ACCOUNT_JSON');admin.initializeApp({credential:admin.credential.cert(JSON.parse(raw)),databaseURL:process.env.FIREBASE_DATABASE_URL});}
const db=admin.firestore();
const SESSION_SECRET=process.env.SESSION_SECRET||'change-this-session-secret';
const clean=(v,m=500)=>String(v??'').trim().slice(0,m);
const escUser=v=>clean(v,30).toLowerCase().replace(/[^a-z0-9_.-]/g,'');
function sign(v){return crypto.createHmac('sha256',SESSION_SECRET).update(v).digest('hex')}
function cookie(req){const c={};(req.headers.cookie||'').split(';').forEach(x=>{const i=x.indexOf('=');if(i>0)c[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim())});return c}
function setSession(res,id){const body=`${id}.${Date.now()+1000*60*60*24*30}`;res.setHeader('Set-Cookie',`bs_session=${encodeURIComponent(body+'.'+sign(body))}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000`)}
function userId(req){const p=(cookie(req).bs_session||'').split('.');if(p.length!==3||Number(p[1])<Date.now()||sign(`${p[0]}.${p[1]}`)!==p[2])return null;return p[0]}
async function me(req){const id=userId(req);if(!id)return null;const s=await db.collection('users').doc(id).get();return s.exists?{id:s.id,...s.data()}:null}
async function requireUser(req,res,next){const u=await me(req);if(!u)return res.status(401).json({error:'Login required.'});req.user=u;next()}
function safeUser(u){return{id:u.id,username:u.username,displayName:u.displayName||u.username,bio:u.bio||'',avatarUrl:u.avatarUrl||'',followersCount:u.followersCount||0,followingCount:u.followingCount||0}}
function hashPassword(p,salt=crypto.randomBytes(16).toString('hex')){return new Promise((resolve,reject)=>crypto.scrypt(String(p),salt,64,(e,b)=>e?reject(e):resolve(`${salt}:${b.toString('hex')}`)))}
function checkPassword(p,stored){return new Promise((resolve,reject)=>{const [salt,h]=String(stored).split(':');crypto.scrypt(String(p),salt,64,(e,b)=>{if(e)return reject(e);resolve(crypto.timingSafeEqual(Buffer.from(h,'hex'),b))})})}
async function imgBB(base64){const key=process.env.IMGBB_API_KEY;if(!key)throw Error('IMGBB_API_KEY is not configured.');const fd=new FormData();fd.append('key',key);fd.append('image',String(base64).replace(/^data:image\/[^;]+;base64,/,'').replace(/^data:[^;]+;base64,/,'').replace(/\s/g,''));const r=await fetch('https://api.imgbb.com/1/upload',{method:'POST',body:fd});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.error?.message||'Image upload failed.');return d.data.url}
function now(){return admin.firestore.FieldValue.serverTimestamp()}
function id(){return crypto.randomBytes(12).toString('hex')}
app.get('/api/public/config',(req,res)=>res.json({appName:'BlueWave',imgbbConfigured:!!process.env.IMGBB_API_KEY}));
app.post('/api/auth/register',async(req,res)=>{try{const username=escUser(req.body.username),password=String(req.body.password||'');const displayName=clean(req.body.displayName,60)||username;if(!/^[a-z0-9_.-]{3,24}$/.test(username))throw Error('Username must be 3–24 characters.');if(password.length<6)throw Error('Password must be at least 6 characters.');const ref=db.collection('users').doc(username),old=await ref.get();if(old.exists)throw Error('Username already exists.');const passwordHash=await hashPassword(password);await ref.set({username,displayName,bio:'',avatarUrl:'',passwordHash,followersCount:0,followingCount:0,createdAt:now()});setSession(res,username);const u=await ref.get();res.json({ok:true,user:safeUser({id:ref.id,...u.data()})})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const username=escUser(req.body.username),s=await db.collection('users').doc(username).get();if(!s.exists||!(await checkPassword(req.body.password,s.data().passwordHash)))throw Error('Invalid username or password.');setSession(res,username);res.json({ok:true,user:safeUser({id:s.id,...s.data()})})}catch(e){res.status(401).json({error:e.message})}});
app.post('/api/auth/logout',(req,res)=>{res.setHeader('Set-Cookie','bs_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/api/auth/me',async(req,res)=>{const u=await me(req);res.json({user:u?safeUser(u):null})});
app.post('/api/media/upload',requireUser,async(req,res)=>{try{const data=clean(req.body.data,7*1024*1024);if(!/^data:image\/(jpeg|png|webp|gif);base64,/i.test(data))throw Error('Only JPG, PNG, WEBP or GIF images are supported.');res.json({ok:true,url:await imgBB(data)})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/feed',requireUser,async(req,res)=>{try{const following=await db.collection('follows').where('followerId','==',req.user.id).get();const ids=[req.user.id,...following.docs.map(x=>x.data().followingId)];let posts=[];for(let i=0;i<ids.length;i+=10){const chunk=ids.slice(i,i+10);const s=await db.collection('posts').where('authorId','in',chunk).orderBy('createdAt','desc').limit(50).get();posts.push(...s.docs.map(d=>({id:d.id,...d.data()})))}posts.sort((a,b)=>(b.createdAt?._seconds||0)-(a.createdAt?._seconds||0));const out=[];for(const p of posts.slice(0,60)){const a=await db.collection('users').doc(p.authorId).get();out.push({...p,author:a.exists?safeUser({id:a.id,...a.data()}):null})}res.json({posts:out})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/posts',requireUser,async(req,res)=>{try{const text=clean(req.body.text,1000),imageUrl=clean(req.body.imageUrl,1000);if(!text&&!imageUrl)throw Error('Write something or add a photo.');const ref=db.collection('posts').doc();await ref.set({authorId:req.user.id,text,imageUrl,likesCount:0,commentsCount:0,createdAt:now()});res.json({ok:true,id:ref.id})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/posts/:id/like',requireUser,async(req,res)=>{try{const ref=db.collection('postLikes').doc(`${req.params.id}_${req.user.id}`),s=await ref.get();if(s.exists){await ref.delete();await db.collection('posts').doc(req.params.id).update({likesCount:admin.firestore.FieldValue.increment(-1)})}else{await ref.set({postId:req.params.id,userId:req.user.id,createdAt:now()});await db.collection('posts').doc(req.params.id).update({likesCount:admin.firestore.FieldValue.increment(1)})}res.json({ok:true,liked:!s.exists})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/posts/:id/comments',requireUser,async(req,res)=>{const s=await db.collection('comments').where('postId','==',req.params.id).orderBy('createdAt','asc').limit(100).get();const rows=[];for(const d of s.docs){const x=d.data(),u=await db.collection('users').doc(x.userId).get();rows.push({id:d.id,...x,author:u.exists?safeUser({id:u.id,...u.data()}):null})}res.json({comments:rows})});
app.post('/api/posts/:id/comments',requireUser,async(req,res)=>{try{const text=clean(req.body.text,500);if(!text)throw Error('Comment is empty.');await db.collection('comments').add({postId:req.params.id,userId:req.user.id,text,createdAt:now()});await db.collection('posts').doc(req.params.id).update({commentsCount:admin.firestore.FieldValue.increment(1)});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/users/search',requireUser,async(req,res)=>{const q=escUser(req.query.q||'');if(!q)return res.json({users:[]});const s=await db.collection('users').orderBy('username').startAt(q).endAt(q+'\uf8ff').limit(20).get();res.json({users:s.docs.map(d=>safeUser({id:d.id,...d.data()}))})});
app.get('/api/users/:username',requireUser,async(req,res)=>{const s=await db.collection('users').doc(escUser(req.params.username)).get();if(!s.exists)return res.status(404).json({error:'User not found.'});const u={id:s.id,...s.data()},f=await db.collection('follows').doc(`${req.user.id}_${s.id}`).get();res.json({user:safeUser(u),following:f.exists})});
app.post('/api/users/:username/follow',requireUser,async(req,res)=>{try{const target=escUser(req.params.username);if(target===req.user.id)throw Error('You cannot follow yourself.');const t=await db.collection('users').doc(target).get();if(!t.exists)throw Error('User not found.');const ref=db.collection('follows').doc(`${req.user.id}_${target}`),s=await ref.get();if(s.exists){await ref.delete();await db.collection('users').doc(req.user.id).update({followingCount:admin.firestore.FieldValue.increment(-1)});await db.collection('users').doc(target).update({followersCount:admin.firestore.FieldValue.increment(-1)})}else{await ref.set({followerId:req.user.id,followingId:target,createdAt:now()});await db.collection('users').doc(req.user.id).update({followingCount:admin.firestore.FieldValue.increment(1)});await db.collection('users').doc(target).update({followersCount:admin.firestore.FieldValue.increment(1)})}res.json({ok:true,following:!s.exists})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/users/:username/posts',requireUser,async(req,res)=>{const s=await db.collection('posts').where('authorId','==',escUser(req.params.username)).orderBy('createdAt','desc').limit(60).get();res.json({posts:s.docs.map(d=>({id:d.id,...d.data()}))})});
app.get('/api/users/:username/followers',requireUser,async(req,res)=>{const s=await db.collection('follows').where('followingId','==',escUser(req.params.username)).limit(100).get();const rows=[];for(const d of s.docs){const u=await db.collection('users').doc(d.data().followerId).get();if(u.exists)rows.push(safeUser({id:u.id,...u.data()}))}res.json({users:rows})});
app.get('/api/users/:username/following',requireUser,async(req,res)=>{const s=await db.collection('follows').where('followerId','==',escUser(req.params.username)).limit(100).get();const rows=[];for(const d of s.docs){const u=await db.collection('users').doc(d.data().followingId).get();if(u.exists)rows.push(safeUser({id:u.id,...u.data()}))}res.json({users:rows})});
app.post('/api/profile/update',requireUser,async(req,res)=>{try{const data={displayName:clean(req.body.displayName,60),bio:clean(req.body.bio,280),avatarUrl:clean(req.body.avatarUrl,1000)};await db.collection('users').doc(req.user.id).update(data);const u=await db.collection('users').doc(req.user.id).get();res.json({ok:true,user:safeUser({id:u.id,...u.data()})})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/search',requireUser,async(req,res)=>{const q=clean(req.query.q,80).toLowerCase();if(!q)return res.json({users:[],posts:[]});const us=await db.collection('users').orderBy('username').startAt(q).endAt(q+'\uf8ff').limit(10).get();const ps=await db.collection('posts').where('text','>=',q).where('text','<=',q+'\uf8ff').limit(10).get().catch(()=>({docs:[]}));res.json({users:us.docs.map(d=>safeUser({id:d.id,...d.data()})),posts:ps.docs.map(d=>({id:d.id,...d.data()}))})});
app.get('/api/admin/stats',async(req,res)=>res.status(403).json({error:'Admin module not enabled in this social starter.'}));
app.use(express.static('public'));
module.exports=app;
